### ISSUE TITLE
Introducing the Team Members

### ISSUE THREAD

**Issue by aemresafak** [bounswe/bounswe2023group4#1]
### Description:
In order to promote transparency, to facilitate collaboration, and to improve accountability, each team member should introduce themselves in the wiki section of this repository. Each team member should conform to the template decided by the team for introducing themselves. Please refer to [Batuhan's introduction](https://github.com/bounswe/bounswe2023group4/wiki/Emre-Batuhan-Göç) of himself for the template details.

### Tasks
- [x] #2 
- [x] #3 
- [x] #4
- [x] #5
- [x] #6
- [x] #7
- [x] #8
- [x] #9

**Comment by aemresafak** [comment]
Here is the task list for this issue:
- [ ] #2 
- [ ] #3 
- [ ] #4
- [ ] #5
- [ ] #6
- [ ] #7
- [ ] #8

**Comment by AliAlperenSonmez** [comment]
Introduction page is created
