### ISSUE TITLE
Creating Issue Template , Issue Rules and Meeting Notes Template 

### ISSUE THREAD

**Issue by EmreBatuhan** [bounswe/bounswe2023group4#13]
To achieve standardized issues and meeting notes , templates for the meeting notes and issues is decided to be created in the wiki page.

**Comment by YigitSekerci** [comment]
My suggestion for issue template, its simple but I guess enough:

Problem Definition:
- Define the basis of the problem
- Writing down a good problem statement is more important than coming up with a good solution.

Context / Screenshots:
- Give some context / link / documents / what you're trying to accomplish

Acceptance Criteria:
- What needs to be done to be able to accept this issue as completed

Suggested solution
- If you have something in mind write it here.

**Comment by YigitSekerci** [comment]
By the way, I don't think we need to show the issue template in wiki. As far as I know you can choose template while creating issue. So, instead we may write guideline about how to create issue with template.

**Comment by EmreBatuhan** [comment]
Thank you for the suggestions Yiğit. I will benefit from them while creating issue template and update the issue rules so that they indicate your suggestions.

**Comment by EmreBatuhan** [comment]
I have created issue rules and meeting notes template pages. I also created a generic issue template. My work is waiting to be reviewed.
