### ISSUE TITLE
Configure Labels

### ISSUE THREAD

**Issue by YigitSekerci** [bounswe/bounswe2023group4#14]
Problem Definition:
- We need more labels to classify issues.

Acceptance Criteria:
- List the labels that are useful and good to have.

Suggested solution
- Look other issue management tools such as Linear, Shortcut, ClickUp.
- Look to old repos in bounswe
- Look popular repos, start with the ones that with researched.

**Comment by YigitSekerci** [comment]
- Apache Lucene (Emre Batuhan Göç fav repo): More than 600 labels. Most of the labels are similar and probably auto generated. We need to find more fundamental labels.
- Risc-v Tools (Ali Nasra fav repo): No useful label, probably they didn't care.
- Compose Samples (Ahmet Emre fav repo):
   Have priority labels but naming not good.
- Sidekiq (My fav repo): No useful label.
- ML-For-Beginners (Enes Furkan fav repo): Issue section is private.
- Tensorflow (Ali Alperen fav repo): 
  Dependencies: Pull requests that update a dependency file
  Other label naming are not good.
- React-Native (Selin Işık fav repo): 
  Platform X: issues related with x platform
  Type Breaking Change
 - TatilSepeti Turkish ChatBot (Yusuf Suat fav repo): No new label.
 - Axios (Halil Özkan fav repo): 
  GitHub Actions: Pr that updates Github Action Codes.
  They are using Linear.

**Comment by YigitSekerci** [comment]
Popular websites:
> From Internet

Bug, Feature Request, Enhancement, Documentation, Design, Security, Performance, Testing, Infrastructure, Help Wanted.

> Popular Apps in general:
Since they allow adding/removal of labels, they have basic labels. 

States:
- Backlog
- Todo
- In Progress
- In Review
- Done

Priority:
- Urgent
- High
- Normal
- Low

**Comment by YigitSekerci** [comment]
I have looked old repos in bounswe and find the labels that we can need. Then, I have combined them with the other useful ones that I have found in research.

**Comment by YigitSekerci** [comment]
I think these labels are enough for now, we may add or remove labels on the way but please comment if you have a good label in mind.

**Comment by AliNasra** [comment]
The group has tentatively approved this label collection. In the upcoming weeks, further scrutiny would follow, and the collection shall be refined by removing unused labels. This concludes this task.
