### ISSUE TITLE
Wiki Update

### ISSUE THREAD

**Issue by selinisik** [bounswe/bounswe2023group4#142]
### Problem Definition

We have friends who left the group and new friends who joined the group. For this reason, the wiki needs to be updated. Also weekly progress report must be added to wiki.

- [x] #146 
- [x] #149 
- [x] #150
- [x] #155

**Comment by selinisik** [comment]
I have updated the readme, wiki homepage and sidebar.

**Comment by Sefik-Palazoglu** [comment]
Looks good to me!
