### ISSUE TITLE
Update Moderator & Jury and Point System Sequence Diagrams

### ISSUE THREAD

**Issue by EmreBatuhan** [bounswe/bounswe2023group4#144]
### Problem Definition

This is a division of the issue #143. This part only consists of Moderator & Jury Sequence Diagrams.

**Comment by EmreBatuhan** [comment]
<details><summary><h3>Moderator & Jury Diagram 1<h3></summary>
  <ul>
    <li><div><img " src="https://github.com/bounswe/bounswe2023group4/assets/93476131/1d9adc0a-6f4b-4987-bb4c-e5a602b499d8"> </div></li>
  </ul>
</details>

<details><summary><h3>Moderator & Jury Diagram 2<h3></summary>
  <ul>
    <li><div><img " src="https://github.com/bounswe/bounswe2023group4/assets/93476131/ba3b246a-8a78-42a8-aa80-3536ed93ce9b"> </div></li>
  </ul>
</details>

<details><summary><h3>Moderator & Jury Diagram 3<h3></summary>
  <ul>
    <li><div><img " src="https://github.com/bounswe/bounswe2023group4/assets/93476131/1b99b490-5dc2-409c-956f-f2bee61c5e49"> </div></li>
  </ul>
</details>

<details><summary><h3>Moderator & Jury Diagram 4<h3></summary>
  <ul>
    <li><div><img " src="https://github.com/bounswe/bounswe2023group4/assets/93476131/56857589-e1d5-472f-a971-ab57e3f38345"> </div></li>
  </ul>
</details>

<details><summary><h3>Moderator & Jury Diagram 4<h3></summary>
  <ul>
    <li><div><img " src="https://github.com/bounswe/bounswe2023group4/assets/93476131/56857589-e1d5-472f-a971-ab57e3f38345"> </div></li>
  </ul>
</details>
![point_system_sequence](https://github.com/bounswe/bounswe2023group4/assets/93476131/5476b4cd-5d4f-4074-8dfb-5804b7655dd4)

![point_system_sequence_2](https://github.com/bounswe/bounswe2023group4/assets/93476131/8fd3b9b1-13b5-4ca3-bbba-375894dab06b)

**Comment by Sefik-Palazoglu** [comment]
Looks good to me!
