### ISSUE TITLE
Create Introduction Page of Şefik Palazoğlu

### ISSUE THREAD

**Issue by Sefik-Palazoglu** [bounswe/bounswe2023group4#146]
### Problem Definition

As described in #142 , each team member should introduce themselves in the wiki page conforming to the template. Currently, introduction page for @Sefik-Palazoglu  is missing.

**Comment by Sefik-Palazoglu** [comment]
Done: https://github.com/bounswe/bounswe2023group4/wiki/%C5%9Eefik-Palazo%C4%9Flu
Added link to wiki page: https://github.com/bounswe/bounswe2023group4/wiki

**Comment by enfurars** [comment]
Great job! I am closing the issue.
