### ISSUE TITLE
Revising and updating the Poll System Sequence Diagrams (1-5)

### ISSUE THREAD

**Issue by AliNasra** [bounswe/bounswe2023group4#147]
### Problem Definition

For an enhanced and expedited implementation, the diagrams shall be revised to accommodate missing or newly added requirements pertinent to the poll system.

### Suggested Solutions

The recommended changes shall be shared with the other team members and, once approved, shall be uploaded to the wiki.

**Comment by AliNasra** [comment]
An initial draft has been delivered and intragroup discussions are ongoing regarding potential modification.

**Comment by EmreBatuhan** [comment]
For the second week, we have assigned you 6th Poll System Sequence Diagram.

**Comment by AliNasra** [comment]
The polls were reviewed and approved by the assigned team members. Hence, I am closing this issue.
