### ISSUE TITLE
Getting Familiar with Project Resources for Şefik Palazoğlu

### ISSUE THREAD

**Issue by Sefik-Palazoglu** [bounswe/bounswe2023group4#148]
### Problem Definition

New members should get familiar with project resources such as diagrams, the repository, and the wiki. This issue is aimed at tracking progress of @Sefik-Palazoglu .

### Acceptance Criteria

A short explanation of general understanding of the general structure of the project as a reply to this issue.

**Comment by Sefik-Palazoglu** [comment]
This project has this repository, and the wiki as its source of general information. In the wiki we have Requirements and Diagrams that explains what the project is and how we are approaching to build it. We are essentially making a prediction/poll application with points to be earned for correct predictions. People can sign up with their e-mails or through Google authentication. We have Guests and Members. Briefly, Guests only have viewing capabilities since they do not own an account. Members own an account, so they have the privilage of opening pools, voting etc.
We planned that polls would have types or tags corresponding to the subject it is on. This brings us to the Domain-Specific Points that Users can earn for correctly answering a prediction poll. There is also General Points which are not bound to any subject.
We envision that giving members points and badges depending on their success on the predictions will increase the interactivity on the app. The details are in the Requirements page.
There is also Moderator and Jury roles explained in the Requirements Page.
The diagrams consists of:
- Class Diagrams illustrates the relationship between objects in our project.
- Sequence Diagrams illustrates the flow of the user experience and what happens in the project.
- Use Case Diagrams illustrates capability of Users (Members, Users, Moderators, Juries etc.) within the system.

**Comment by selinisik** [comment]
This description explains our project perfectly. Welcome to the group 🎉
