### ISSUE TITLE
Create Introduction Page of Serhat Hebun Şimşek

### ISSUE THREAD

**Issue by Sefik-Palazoglu** [bounswe/bounswe2023group4#149]
### Problem Definition

As described in #142 , each team member should introduce themselves in the wiki page conforming to the template. Currently, introduction page for @simsekhebun is missing.

**Comment by simsekhebun** [comment]
Created my introduction page which can be accessed [here](https://github.com/bounswe/bounswe2023group4/wiki/Serhat-Hebun-%C5%9Eim%C5%9Fek). Also added it to the [wiki](https://github.com/bounswe/bounswe2023group4/wiki) and who we are section on the sidebar.

**Comment by Sefik-Palazoglu** [comment]
LGTM!
