### ISSUE TITLE
Re-verify the requirements

### ISSUE THREAD

**Issue by selinisik** [bounswe/bounswe2023group4#151]
### Problem Definition

Before moving forward with the project, we must review our requirements and fix any missing or inconsistent points.

**Comment by simsekhebun** [comment]
Updated user requirements. Added 1.1.1.7, 1.1.2.2.3, 1.1.4.8, 1.1.4.9, 1.1.5.2.3, 1.1.7.2.6, 1.1.8 Notifications section and 1.1.8.1, 1.1.8.2.

**Comment by aemresafak** [comment]
**New Proposal for Non-functional Requirements**

## 2. Non-Functional Requirements 
<details>
 <summary> 
  2.1 Portability and Compatibility Requirements
 </summary>
 <ul>
  <li> 2.1.1 The website shall be able to run on Google Chrome, Yandex, Safari, Microsoft Edge and Firefox seamlessly, any failure regarding its specified performance and scalability requirements and any change in its behavior.</li>
  <li> 2.1.2 The application shall be able to run on Android API 24 and later versions seamlessly with consistent behavior.</li>
 </ul>
</details>

<details>
 <summary> 
  2.2 Performance and Scalability Requirements
 </summary>

### 2.2.1 Web Application Performance

- **2.2.1.1** The web application's initial load time shall not exceed 5 seconds on broadband connections.
- **2.2.1.2** For subsequent page loads (after caching), the load time should not exceed 2 seconds.
- **2.2.1.3** Asynchronous web requests should receive a response within 1 second under normal load conditions.

### 2.2.2 Mobile Application Performance

- **2.2.2.1** The mobile app should launch within 3 seconds from a stopped state on devices released within the past three years.
- **2.2.2.2** Screen transition within the mobile application should not exceed 1 second.
- **2.2.2.3** API calls initiated from the mobile application to the backend should receive a response within 1.5 seconds under normal load conditions.

### 2.2.3 Scalability

- **2.2.3.1** The system should be scalable horizontally, allowing for the addition of servers or instances without significant changes to system architecture.

### 2.2.4 Data Transfer

- **2.2.4.1** Images and media loaded in the mobile and web apps should be optimized for their respective platforms to reduce unnecessary data transfer.

</details>

<details>
 <summary> 
  2.3 Reliability, Maintainability, Availability Requirements
 </summary>

 _The Reliability, Maintainability, Availability requirements will be decided at the further stages of the project._

</details>

<details>
 <summary> 
  2.4 Security Requirements
 </summary>
 <ul>
  <li> 2.4.1 An unauthorized access to admin panel shall be blocked by defining different login flows and different user roles as user actions. </li>
  <li> 2.4.2 All nicknames shall be different from each other.</li>
  <li> 2.4.3 KVKK provisions shall be applied.  </li>
 </ul>
</details>

<details>
 <summary> 
  2.5 Localization Requirements
 </summary>
_These are localization requirements for Turkey. If our customer decides to enter other markets, suitable localization requirements will be applied._
 <ul>
  <li> 2.5.1 The language of the website shall be Turkish. </li>
  <li> 2.5.2 The date format shall be date.month.year.</li>
  <li> 2.5.3 The context of the website shall be proper to the regulations of Turkey. </li>
  <li> 2.5.4 The website shall be able to show Turkish characters without any problem. </li>
  <li> 2.5.5 The sorting algorithms(if any) used on the website shall be according to Turkish alphabet. </li>
 </ul>
</details>

I was responsible for reviewing the non-functional requirements. I changed the part about the Performance and Scalability radically. Moreover, there was a part about usability requirements and they constituted of functional requirements. Thus, I have removed that part completely. Above is the **new** version. You can find the original version from the wiki page. I also paste it below for convenience.

**Old Non-functional Requirements**

## 2. Non-Functional Requirements 
<details>
 <summary> 
  2.1 Portability and Compatibility Requirements
 </summary>
 <ul>
  <li> 2.1.1 The website shall be able to run on Google Chrome, Yandex, Safari, Internet Explorer and Firefox without any extra work, any failure regarding its specified performance and scalability requirements and any change in its behavior.</li>
  <li> 2.1.2 The application shall be able to run on Android API 24 and later versions without any extra work and change in the behavior.</li>
  <li> 2.1.3 The application shall be able to run on iOS 16.0 and later versions without any extra work and change in the behavior.</li>
 </ul>
</details>

<details>
 <summary> 
  2.2 Performance and Scalability Requirements
 </summary>
 <ul>
  <li> 2.2.1 The website's page load time shall be maximum 6 seconds. </li>
  <li> 2.2.2 The website's page load time should be under 3 seconds on average. </li>
  <li> 2.2.3 The website should have an average response time between 0.1 - 1 second. </li>
 </ul>
</details>

<details>
 <summary> 
  2.3 Reliability, Maintainability, Availability Requirements
 </summary>

 _The Reliability, Maintainability, Availability requirements will be decided at the further stages of the project._

</details>

<details>
 <summary> 
  2.4 Security Requirements
 </summary>
 <ul>
  <li> 2.4.1 An unauthorized access to admin panel shall be blocked by defining different login flows and different user roles as user actions. </li>
  <li> 2.4.2 All nicknames shall be different from each other.</li>
  <li> 2.4.3 KVKK provisions shall be applied.  </li>
 </ul>
</details>

<details>
 <summary> 
  2.5 Localization Requirements
 </summary>
_These are localization requirements for Turkey. If our customer decides to enter other markets, suitable localization requirements will be applied._
 <ul>
  <li> 2.5.1 The language of the website shall be Turkish. </li>
  <li> 2.5.2 The date format shall be date.month.year.</li>
  <li> 2.5.3 The context of the website shall be proper to the regulations of Turkey. </li>
  <li> 2.5.4 The website shall be able to show Turkish characters without any problem. </li>
  <li> 2.5.5 The sorting algorithms(if any) used on the website shall be according to Turkish alphabet. </li>
 </ul>
</details>

<details>
 <summary> 
  2.6 Usability Requirements
 </summary>
_Adequately trained users are considered to be the appropriate users for testable usability requirements._
 <ul>
  <li> 2.6.1 Users should be adequately trained by aid of simple instructions when they are first sign-up to the website. </li>
  <li> 2.6.2 The appropriate member should be able to login to the system.</li>
  <li> 2.6.3 The appropriate member should be able to post a new poll. </li>
  <li> 2.6.4 The appropriate member should be able to predict on a poll. </li>
  <li> 2.6.5 The appropriate member should be able to personalize his/her profile. </li>
  <li> 2.6.6 Components in the page should have overlay description for special members. </li>
 </ul>
</details>

**Comment by FatihAkgoz** [comment]
I have reviewed the System Requirements (1.2) and was not able to find any inconsistencies or errors.

**Comment by aemresafak** [comment]
The team deems reviewing and updating the System Requirements (1.2) very crucial. Thus, I will re-review the requirements for System Requirements.

**Comment by aemresafak** [comment]
1.2.2.1 System shall grant points to the members according to the proximity of their voting time to the poll posting time. The granted points will be determined by a linear function in which the closer the voter gets to the deadline the lower the reward points will be.
1.2.3.6 If no nine moderators accept the join-the-jury request in six hours, the system shall send the join-the-jury request again to each appropriate moderator but this time with doubled prize. The system shall repeat this process until a jury of nine is gathered. Moreover, the system will set the previous requests to passive.
1.2.3.8 If jury does not answer the poll in time, the system shall send the join-the-jury request again to each appropriate moderator again but this time with doubled prize. Moreover, the system shall disarrange the previous jury.

**Comment by selinisik** [comment]
LGTM!
