### ISSUE TITLE
Creating a responsibility assignment matrix 

### ISSUE THREAD

**Issue by selinisik** [bounswe/bounswe2023group4#152]
### Problem Definition

Before moving forward with the project, we need to assign clear roles and responsibilities to team members and define their duties correctly.

**Comment by enfurars** [comment]
I have created the table, now I need to know who is responsible of what in sub-teams and in general. Then I can update the matrix and put it on our wiki page.

**Comment by enfurars** [comment]
I have created and submitted the [RAM](https://github.com/bounswe/bounswe2023group4/wiki/RAM). You can check it from the link and also it is in our wiki page. Can someone check it and close the issue if everything is alright?

**Comment by YigitSekerci** [comment]
Looks good to me but it is better to have more review.
