### ISSUE TITLE
Decide on what technologies are going to be used for the front-end 

### ISSUE THREAD

**Issue by selinisik** [bounswe/bounswe2023group4#153]
### Problem Definition

We need to decide which libraries will be used in the frontend of the project.

**Comment by enfurars** [comment]
I recommend having a meeting with the frontend team to decide on our options, then we can discuss them with the team for convenience.

**Comment by enfurars** [comment]
After discussions we have decided to use React, HTML, CSS and Javascript for the frontend of the project.
