### ISSUE TITLE
Create Introduction Page of Kutay Saran

### ISSUE THREAD

**Issue by selinisik** [bounswe/bounswe2023group4#155]
### Problem Definition

As described in https://github.com/bounswe/bounswe2023group4/issues/142 , each team member should introduce themselves in the wiki page conforming to the template. Currently, introduction page for Kutay Saran is missing.

**Comment by kutaysaran** [comment]
Done :  https://github.com/bounswe/bounswe2023group4/wiki/Kutay-Saran
