### ISSUE TITLE
Getting Familiar with Project Resources for Fatih Akgöz

### ISSUE THREAD

**Issue by selinisik** [bounswe/bounswe2023group4#158]
### Problem Definition

New members should get familiar with project resources such as diagrams, the repository, and the wiki. This issue is aimed at tracking progress of @FatihAkgoz .

### Acceptance Criteria

A short explanation of general understanding of the general structure of the project as a reply to this issue.

**Comment by FatihAkgoz** [comment]
This project is on  creating and voting in polls with social features. This application should have necessary security and moderation components by the time we implement it. There is also a detailed point system for the polls.
