### ISSUE TITLE
Decide requirements for the project & Create Wiki for requirements

### ISSUE THREAD

**Issue by YigitSekerci** [bounswe/bounswe2023group4#16]
### Problem Definition

We had our meeting with Utkan. We have many idea, but we didn't decide whether those are required or not (nice to have).
We need to decide requirements and create the wiki page.

### Problem Context

* You can look old repos in bounswe to understand general idea in requirement pages. 

### Acceptance Criteria

* Decide requirements under this issue
* Create requirements wiki page 

### Suggested Solutions

* Everybody can add their opinion under this issue about requirements
* Then, I can create requirements page
* After that, we can review it for further improvements

**Comment by AliNasra** [comment]
Here is my take on this matter!
**Possible design requirements:**
1- Users should be able to post polls. 
2- Anonymous posting should be allowed, albeit with a cost.
3- Polls should include a comment section where discussions should be held regarding the polls’ topics.
4- Polls should be categorized semantically under specific tags.
5- Multiple opportunities for vote casting should be provided, albeit with a cost. 
6- The reward of a prescient prediction should be commensurate with the earliness of the prediction.
7- Users should be able to share their achievements on social media platforms.
8- Users should be able to add friends or follow other users whose polls they find interesting.
9- Users should specify the type of options to be provided in the poll, either discrete or continuous. In the case of continuous options, values should be clustered in discrete bands.  
10- Users should define a tentative end date for each poll they open. 
11- The platform should provide an analysis of the users’ performance in multiple categories.
12- The results of public-related polls should be confirmed by reputed journalism agencies. 
**Nice to have:**
1- Adult content ought to be censored for underage users.  
2- Users might be asked to provide personal info regarding their vote-casting settings for more insightful pattern reports. 
3- Users might be asked to share a link to a website according to whose content they cast their votes.

**Comment by YigitSekerci** [comment]
> My opinion
## Requirements
* Guest users should be able to interact with allowed basic features in website without login.
* Auth flow is required for login.
* Onboarding is required for new users to understand how things work.
* Users should be able to use polls that created by our team. (Official polls)
* Users should be able to post polls with some cost.
* Users should be able to follow other users.
* Users should be able to look other users profiles.
* Users should be able to send private messages to other users.
* Users should be able to search wanted post among the posts.
* Users should be able to categorize posts.
* Users should have achievements according to their stats.
* Users should be able to share these achievements with premade template in social platforms.
* Users should be able to see their stats.
* Users should be able to customize their profiles.
* Users should have mini avatar that we can show in profile or chat.
* Users should be able to change their avatar.
* Users should be able to show their predictions in their profile.
* Users should be able hide the unwanted predictions in their profile.
* Users should be able to add bio to their profiles.
* Users should be able create friends only polls.
* Users should be able to change the settings of polls for the cost of not having reward or achievement at the end of the poll.
* Users should be able to give feedback.
* There should be community guidelines for users to follow.
* Posts should be tagged by category with semantic tagging.
* Posts should have filterable, sortable comments.
* Posts should be sharable in social media.
* Posts' result confirmation should be shown in post.
* Posts may have a end date depending on the type of poll.
* Posts may distribute the reward according the closeness of the prediction.
* Posts reward mechanism should be well defined, clear for every user.
* There should be exception catch flow for getting information. (like Firebase Crashlytics)

## Nice to have:
* Referral system for users.
* Hot zones that can increase poll rewards.(like Pokemon GO)
* Adult content censorship
* Poll suggestion system
* Public API with key system for advanced users to be able to automate or check some features.
* Automated chat bot for user support. (like Intercom)
* How to articles for users to learn about app.
* Featured polls created by our team. (Popular polls)
* Weekly or daily poll template to compete users.
* Leaderboard for satisfaction

**Comment by AliNasra** [comment]
There is a semblance of consensus regarding the requirements of the project. Nevertheless, previous discussions and deliberations have brought to light some concerning debates.
1- How do we confirm the integrity and the correctness of the polls' results once they are declared over?
2- How would we discretize continuous values?
3- How would we handle polls with far-due days? Who should oversee their conclusions? The user or the platform management itself?
4- How would tackle inappropriate dialogue on the platform? Do we need moderation or rather a sophisticated monitoring API?
5- Would the votes have weighted values premised on the proximity of vote-casting to the due date of the poll? If so, how should users be able to post polls with indefinite due dates?

**Comment by enfurars** [comment]
### Possible Requirements (My opinion)

- Users should be logged in(in some way) before they contribute to polls or posting a new poll.
- Users should have nicknames which can be seen by other users. 
- Each user should have a profile which can be personalized by them.
- Users should have an option to predict privately and reveal the prediction on a later date if they want.
- Every user should have exactly one prediction for any poll they contributed. (They should not have more than one prediction at the same time for a certain poll.
- There should be certain mechanisms to end a poll.
- Users should be able to change their prediction before the end date of the poll.
- There should be a ranking system in which users gain points when they predict true and lose otherwise. These points may also be used to open a new poll.
- There should be a mechanism which calculates new ranks of attended users when a poll ends.
- Each poll should be categorized appropriate to semantic tagging.
- There should be a friendship mechanism between users.
- There should be a mechanism to ensure that some polls can be attended only with an invitation by the host.

**Comment by skywllker** [comment]
## My commends:
* Users could open pools and determine capacity of that pools and the bet rates, other users should attend that pools, like a market system.
* Private pools in determined locations by us
* We can sell our application to the game centers or bars. We should sell the right for open specific pools. We will sell the right because someone should enter the information of who is the winner of bet.
* We should sell the right of starting pools that we can't find who is the winner of that pool. Users that join that pools can complain about the results.
* Invitation only pools.
* System for checking the winner of pools by internet.
* We can use an app like Chat gpt to gain information about a pool.
* We can post information, statistics, guess of important peoples about all pools.

**Comment by selinisik** [comment]
## My opinion about requirements

* Users should have an account to use fundamental features of the platform.
* Users without an account can only access a limited portion of the content inside the platform.
* Users must provide the necessary information during the registration process.
* Users can specify the visibility of some of their information.
* Users must have the right to vote on all polls they have access to (we may need to restrict access to some content for some users, eg: if we have users under 18).
* Users' voting rights (how many times they can vote, whether they can change their votes, etc.) should be determined in advance.
* Users should be able to socialize in the platform with provided features(eg: adding friends, opening a group with their friends etc.).
* Users should only open polls when they meet the prerequisites(eg: it can be determined by the user's level or we can request some points for opening a poll etc.), and polls should contain the necessary information to ensure standardization in poll structure (ex: every survey must have a title and the description field may not be required).
* Users should have a profile page where they can view their correct predictions and achievement items (eg: items such as trophies or stars).
* Users should have a sharing feature that they can use for their profiles, achievements and polls they have opened.
* Users should determine the visibility of their personal information in the answers section of the polls.
* Users should determine the target audience of the polls they open.
* Polls should be categorized using the required information provided by the poll title, and all polls should have at least one tag to categorize.
* Polls should be filterable by tags.
* Poll reward mechanism should be determined taking into account a variety of possible poll samples (eg: discrete or continuous value responses) and should be predefined by the platform's creators.

**Comment by YigitSekerci** [comment]
Thanks to @selinisik, requirements page have been created. We looked many old repos to figure out best structure. We havent managed to finish it yet since we didnt learn to whole structure in class yet but if you have something in your mind please go and update wiki.

**Comment by selinisik** [comment]
We have successfully identified the requirements. Thanks to everyone who contributed.
