### ISSUE TITLE
Research and Study Back-end technologies

### ISSUE THREAD

**Issue by Sefik-Palazoglu** [bounswe/bounswe2023group4#164]
### Problem Definition

Our members need to get familiar with the backend technologies we will use in this project.

**Comment by EmreBatuhan** [comment]
I have followed this video. I have watched half of the video but I have learned quite a lot about node.js.  https://youtu.be/Oe421EPjeBE?si=WsC_tISdouvGajW5

**Comment by Sefik-Palazoglu** [comment]
I have followed this video to review the parts I forgot about node.js: https://www.youtube.com/watch?v=f2EqECiTBL8. I studied for the parts I forgot, so it took about 4 hours

**Comment by simsekhebun** [comment]
I have also studied for the parts I may have forgotten about, since everybody is done I am closing this issue.
