### ISSUE TITLE
Project Initialization for Front-end

### ISSUE THREAD

**Issue by kutaysaran** [bounswe/bounswe2023group4#167]
### Problem Definition

The frontend component needs to be initialized. All discussion relating to setup of frontend project goes in this issue.

**Comment by kutaysaran** [comment]
I have initialized the frontend project. I created the folder structure, I added a router library that enables the navigation among of various components and Ant Design library that contains easy-to-use components for UI.

**Comment by enfurars** [comment]
Well done @kutaysaran! I and @selinisik reviewed the PR and it is merged now. Which concludes this issue.
