### ISSUE TITLE
Mobile Application Project Initialization

### ISSUE THREAD

**Issue by aemresafak** [bounswe/bounswe2023group4#169]
### Problem Definition

As per the decision made by the team this week, we start initializing the projects. As part of this action, me and @YigitSekerci are responsible for initializing the Android project. We shall come together and initialize the mobile project

### Suggested Solutions

Initialize the mobile project and push it to this github repository.

**Comment by YigitSekerci** [comment]
I have created the project in feature/android-project-init branch can you check it and fix if something is wrong in config? @aemresafak

**Comment by YigitSekerci** [comment]
With the help of @aemresafak we finished initialization in https://github.com/bounswe/bounswe2023group4/pull/186 . Task is done.
