### ISSUE TITLE
Do domain analysis for the project

### ISSUE THREAD

**Issue by selinisik** [bounswe/bounswe2023group4#17]
### Problem Definition

We need to do a research on similar projects, and if possible, find people who are knowledgeable about our project topic and contact them.

### Acceptance Criteria

- Do a research and share important results under this issue
- If necessary, the requirements can be changed in the light of the new information we have obtained.

### Suggested Solutions

- Everybody can add their findings under this issue
- Then, we can discuss whether the requirements should be updated
- If it is decided to be updated, the topic can be added to the meeting agenda and discussed at the meeting.

**Comment by AliNasra** [comment]
The majority of reminiscent examples available on the internet are sports-related betting or gambling websites. Taking those websites as a premise for our project is problematic because of the fees charged for the users and the myopic scope of such applications that contradicts the aspired goals of the projects. Predicting the results of a football match is easier thanks to the abundance of resources to confirm the true results and the lack of polls with a continuous domain of possible results.

**Comment by YigitSekerci** [comment]
We may see several obstacles in our way.
### Adult content (Offensive language):
* External libraries can be used to such as: profanity-check (Python), BadWordFilter (Java), Better-Profanity (JavaScript), swearjar (Ruby)

### Prediction Odds
* There are several API's for getting odds but most of them sport related. 
* If we want users to open polls freely it's hard for us to calculate the odds for random event. So we may give them option to search their poll category, if they cannot find their desired category we can close the odds for that poll.
* ChatGPT can give odds for general event such as coin flip however it cannot interpret real data.

**Comment by aemresafak** [comment]
There is a very similar project to ours. It is named PredictIt.

### PredictIt
Here is a short description of the PredictIt: PredictIt is designed to provide a platform for users to engage in a form of "crowdsourced" prediction-making, where individuals with different knowledge and insights can contribute to making more accurate predictions about the future. The platform also serves as a way to track the collective wisdom of its users in real time.

It resembles a gambling application. Users can bet on outcomes of certain events and earn or lose money on their bet. There is a major restriction of PredictIt, however, it is only available in USA.

You can check their [website](https://www.predictit.org/) for more information.
