### ISSUE TITLE
Backend Project Initialization

### ISSUE THREAD

**Issue by EmreBatuhan** [bounswe/bounswe2023group4#170]
### Problem Definition

As per the decision made by the team this week, we start initializing the projects. As part of this action, I am responsible for initializing the backend of the project.

### Suggested Solutions

Initialize the backend and push it to this github repository.

**Comment by EmreBatuhan** [comment]
I am thinking a structure as [this](https://github.com/bounswe/bounswe2023group4/files/12905408/node-app.zip).

**Comment by Sefik-Palazoglu** [comment]
PR has been approved and merged.
