### ISSUE TITLE
Learn kotlin basics

### ISSUE THREAD

**Issue by YigitSekerci** [bounswe/bounswe2023group4#179]
### Problem Definition

Since we chose native android + jetpack compose we need learn kotlin for android coding. Every member of the mobile team should look through internet and learn basics of kotlin via kotlin playgrounds or online compilers.

### Problem Context

This issue is one of the divided issues for mobile research which are indicated in #176.

### Acceptance Criteria

* Learn basic keywords.
* Learn OOP in android
* Learn extension functions and how to use them.

### Suggested Solutions

* https://developer.android.com/kotlin/learn This link may help for those who are new to the language.

**Comment by YigitSekerci** [comment]
I have already known the kotlin language thus I have only looked and learned the changes in latest versions.

**Comment by aemresafak** [comment]
This week I've spent around 4 to 6 hours to learn about kotlin. I've learned about inheritance, data classes, variable types and many more thing about Kotlin.

**Comment by AliAlperenSonmez** [comment]
I have learned Kotlin fundamentals, including basic keywords, object-oriented programming concepts, and extension functions. I have dedicated approximately 5 hours to learning these essential Kotlin concepts.

**Comment by aemresafak** [comment]
Great! We are onboard!
