### ISSUE TITLE
Learn Android basics

### ISSUE THREAD

**Issue by YigitSekerci** [bounswe/bounswe2023group4#180]
### Problem Definition
Android has many concepts and we cannot cover them all at start, but we need to start by basics. Every team member should learn the fundamentals of android. Since the android studio will be our IDE in android every member should learn it also while learning android fundamentals because they tightly depend on each other. Because of IDE's well designed tools, we may reduce our development time significantly.

### Problem Context

This issue is one of the divided issues for mobile research which are indicated in https://github.com/bounswe/bounswe2023group4/issues/176.

### Acceptance Criteria
* Learn android basics
* Learn android studio basics
* Learn to create emulator
* Learn how to run hello world app.
* Learn what does logcat do
* Learn what does app and layout inspectors do

### Suggested Solutions
* For android basic I recommend [this YouTube link](https://www.youtube.com/watch?v=SJw3Nu_h8kk&list=PLQkwcJG4YTCSVDhww92llY3CAnc_vUhsm)  for fast learning.
* Android Studio is well known IDE thus one can find many tutorials about it in YouTube.

**Comment by YigitSekerci** [comment]
I have already known the android basics but there were some info about layout inspector that I haven't known I have learned those topics and I have created new emualator for new android sdk.

**Comment by aemresafak** [comment]
I have installed Android Studio and run a hello world app. Then, i have researched about android basics and studied Activities, Views and other Android basics from Android Documentation. This took around 6 to 10 hours of my time this week. Android is a vast universe, i have a lot more to cover.

**Comment by AliAlperenSonmez** [comment]
I have successfully installed Android Studio, created some basic projects and experimented with emulator to familiarize myself with the development environment. I have also learned logcat command-line tool, and also checked inspectors to learn how to debug layouts and ui. My learning and experimenting process took about 6 hours in total.
