### ISSUE TITLE
Learn theming in jetpack compose.

### ISSUE THREAD

**Issue by YigitSekerci** [bounswe/bounswe2023group4#182]
### Problem Definition

In UI we will use repetitive elements like color, shape and font. Jetpack compose support a way to handle these concept nicely and we need to learn it to have better structured code. Every member should learn theming in jetpack compose.

### Problem Context

* This issue is one of the divided issues for mobile research which are indicated in https://github.com/bounswe/bounswe2023group4/issues/176.

### Acceptance Criteria

* Learn theming in jetpack compose

### Suggested Solutions

* https://developer.android.com/jetpack/compose/designsystems Android's official docs are enough for this issue I guess.

**Comment by YigitSekerci** [comment]
I have already known implementing the theme but I didn't know the Material 3 design I learned those features for designing better theme for our UI.

**Comment by aemresafak** [comment]
I have tried to learn this. I think I know the basics.

**Comment by AliAlperenSonmez** [comment]
I have utilized the official Android documentation as a valuable resource to acquire in-depth knowledge of theming concepts in Jetpack Compose, ensuring our codebase is well-structured and consistent in design.

**Comment by YigitSekerci** [comment]
We made a mistake by combining research issues. Because every members' finish time is different we couldn't close this issue on time. Due to this reason, this issue is completed eight day after its deadline.
