### ISSUE TITLE
Learn Javascript Basics

### ISSUE THREAD

**Issue by selinisik** [bounswe/bounswe2023group4#187]
### Problem Definition

We want everyone on the team to understand the basics of JavaScript, which is a crucial part of building websites. This means knowing things like variables, functions, and how to work with web pages.

### Problem Context

This issue is one of the divided issues for frontend research which are indicated in https://github.com/bounswe/bounswe2023group4/issues/166.

### Acceptance Criteria

* Learn javascript basics( variables, functions, data types,conditional statements ...)
* Run your first website and open in browser.

### Suggested Solutions

* [This website](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics) gives a brief summary of basics and guides you to create your first website 
* [This tutorial](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/) is much more comprehensive and can be useful for most javascript tasks. Javascript basics section can be examined

**Comment by enfurars** [comment]
This week I have studied javascript and used the suggested resources as my guide. It was very helpful for basic concepts of the javascript.

**Comment by kutaysaran** [comment]
Thanks to the suggested resources, I renewed my knowledge about JavaScript.

**Comment by selinisik** [comment]
I have reviewed my knowledge in JavaScript with suggested resources. I have completed JavaScript basics in freecodecamp.

**Comment by AliNasra** [comment]
I have refreshed my knowledge by watching YouTube tutorials and revising the structures and features of the language as featured in old samples that I have written during previous internships.
