### ISSUE TITLE
Learn Javascript ES6 

### ISSUE THREAD

**Issue by selinisik** [bounswe/bounswe2023group4#188]
### Problem Definition

Our goal is to introduce team members to the fundamentals of JavaScript ES6 (ECMAScript 2015) – a modern version of JavaScript that brings powerful new features to the language. We aim to familiarize everyone with ES6 concepts like arrow functions, template literals, const and let declarations, and destructuring. By learning these ES6 features, we can write cleaner, more efficient JavaScript code and take advantage of modern development practices for our web projects.

### Problem Context

This issue is one of the divided issues for frontend research which are indicated in https://github.com/bounswe/bounswe2023group4/issues/166.

### Acceptance Criteria

* Learn arrow functions
* Learn template literals
* Learn destructions, spread and rest operators.

### Suggested Solutions

* [This website](https://www.javascripttutorial.net/es6/) detailly explains all es6 concepts.
* The tutorial mentioned in [#187](https://github.com/bounswe/bounswe2023group4/issues/187) can be used as well.

**Comment by selinisik** [comment]
I've dedicated time to review some important JavaScript ES6 concepts such as destruction, spread operators etc. I have mostly read documentations and reviewed example usages from websites in this task. I believe that these concepts will be important in our project to maintaining a readable and clean code structure.

**Comment by enfurars** [comment]
This was my first time hearing about ES6. So I have read the documentation tutorial and watch some videos about it. I am now more familiar with the features like arrow functions, destructuring and template literals. Now I believe I can use these concepts properly in our project.

**Comment by kutaysaran** [comment]
I've finished the research on JavaScript ES6 as per the defined criteria, gaining proficiency in areas like arrow functions, template literals, and destructuring. My acquired knowledge will contribute to improved coding practices in our frontend project.

**Comment by AliNasra** [comment]
I had a previous experience with ES6. The new features facilitate easier array manipulation. I have written some line codes in order to confirm my comprehension of the concept.
