### ISSUE TITLE
Learn Javascript Arrays

### ISSUE THREAD

**Issue by selinisik** [bounswe/bounswe2023group4#189]
### Problem Definition

Our objective is to equip team members with a strong understanding of JavaScript arrays, a fundamental data structure. This entails learning how to create, manipulate, and utilize arrays effectively in JavaScript. Key topics include array creation, adding and removing elements, accessing data within arrays, and performing common operations like sorting and filtering. Proficiency in arrays is essential for efficient data handling.

### Problem Context

This issue is one of the divided issues for frontend research which are indicated in https://github.com/bounswe/bounswe2023group4/issues/166.

### Acceptance Criteria

* Learn map, filter and reduce functions, which are prerequisites for learning React.js

### Suggested Solutions

* [This website](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) covers all the major array methods and provides good examples of how to use them.

**Comment by enfurars** [comment]
I have studied this subject from this [tutorial](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/#functional-programming). It is also helpful to learn map, filter and reduce methods together with functional programing conventions. It is also guiding you to do some hands on applications.

**Comment by AliNasra** [comment]
I have referred to the link provided by Selin in the issue declaration. It provides a comprehensive and exhaustive overview related to arrays and their functionalities in Javascript. I have also checked out Enes' implementation of the sign-up page which involved lists such as those used for birthdates.

**Comment by selinisik** [comment]
In order to solidify my understanding of JavaScript arrays, I have delved into the provided resources, paying special attention to the map, filter, and reduce functions. These key array methods are crucial for efficient data manipulation, and mastering them is a prerequisite for excelling in React.js development. Through practical examples and comprehensive coverage, I have enhanced my skills in creating, manipulating, and utilizing JavaScript arrays, ensuring I am well-prepared for the project implementation.

**Comment by kutaysaran** [comment]
I've deeply enriched my understanding of JavaScript arrays, mastering both basic and advanced functionalities. Through hands-on practice, I've excelled in data manipulation using methods like map, filter, and reduce. My proficiency in array creation, iteration, and multi-dimensional structures now stands at an advanced level, ready for use in our project.
