### ISSUE TITLE
Sending requirement related questions to the project owner.

### ISSUE THREAD

**Issue by selinisik** [bounswe/bounswe2023group4#19]
### Problem Definition

In our meeting, we realized that we needed more information on some issues before determining the requirements. So, we have discussed about the questions we should send and we will collect and send them to the project owner.

### Acceptance Criteria

Everyone will send their questions to the discord channel until 11:00 on Friday, and the questions will be collected and sent to the project owner.

### Suggested Solutions

While preparing the questions, we should try to include as much detail as possible so that our answers are more useful in determining the requirements.

**Comment by AliNasra** [comment]
The questions were successfully delivered to Utkan, thereby concluding this task.
