### ISSUE TITLE
Learn React Basics

### ISSUE THREAD

**Issue by selinisik** [bounswe/bounswe2023group4#190]
### Problem Definition

Our aim is to introduce team members to the fundamental concepts of React, a popular JavaScript library for building user interfaces. We will cover topics such as component creation, state management, and rendering dynamic content. By mastering these React basics, our team will be well-equipped to create interactive and responsive web applications.

### Problem Context

This issue is one of the divided issues for frontend research which are indicated in https://github.com/bounswe/bounswe2023group4/issues/166.

### Acceptance Criteria

* Learn Functional Components well since we will mostly use them. The reasons are [here](https://www.geeksforgeeks.org/why-it-is-recommended-to-use-functional-components-over-class-components/).
* Create your first component.

### Suggested Solutions

* [This webite](https://www.w3schools.com/REACT/default.asp) covers all basic features of React.js .
* [This website](https://www.geeksforgeeks.org/differences-between-functional-components-and-class-components/) explains difference between functional components and class-based components .
* [This website](https://www.geeksforgeeks.org/reactjs-functional-components/) detailly explains functional components .

**Comment by selinisik** [comment]
I consolidated my knowledge of React through recommended resources, focusing on functional components and practical implementation. By studying articles and building a react component, I gained a solid foundation in react. I have also used this knowledge in our Sign-in Page.

**Comment by kutaysaran** [comment]
After examining the resources recommended by Selin and Enes, I refreshed and strengthened my knowledge about React basics. I utilized these resources while implementing the UI for our sign-up page.
