### ISSUE TITLE
Learn CSS Basics

### ISSUE THREAD

**Issue by selinisik** [bounswe/bounswe2023group4#191]
### Problem Definition

Our objective is to ensure team members grasp the essential concepts of Cascading Style Sheets (CSS) as it plays a pivotal role in styling web elements within JavaScript and React applications. This includes learning how to apply CSS rules to HTML elements for tasks like setting styles, fonts, layouts, and responsiveness.

### Problem Context

This issue is one of the divided issues for frontend research which are indicated in https://github.com/bounswe/bounswe2023group4/issues/166.

### Acceptance Criteria

* Style your javascript project created in [#187](https://github.com/bounswe/bounswe2023group4/issues/187).
* Style your React component created in [#190](https://github.com/bounswe/bounswe2023group4/issues/190).

### Suggested Solutions

* You can pick any section you want to learn from [this tutorial](https://www.freecodecamp.org/learn/2022/responsive-web-design/#learn-css-colors-by-building-a-set-of-colored-markers).
* [This youtube video](https://www.youtube.com/watch?v=1PnVor36_40) briefly explains basic usages of CSS.

**Comment by selinisik** [comment]
I have reviewed my basic CSS knowledge in javascript basics issue by using suggested resources.

**Comment by enfurars** [comment]
I had some previous knowledge on CSS yet the tutorial and suggested YouTube video were helpful. I have remembered the syntax and the concepts of selectors, styles and colors. I have also seen some applications with given examples.

**Comment by kutaysaran** [comment]
I have dedicated time to revisiting and solidifying my foundational knowledge of CSS. To achieve this, I extensively utilized the recommended resources to ensure I possess a strong command of the fundamental principles of CSS.

**Comment by AliNasra** [comment]
I have initialized a react project where I experimented with the CSS file in order to examine each feature and its effects on the overall design. In addition, I have consulted my teammates regarding practices favored with CSS.
