### ISSUE TITLE
Decide the font for the mobile app

### ISSUE THREAD

**Issue by YigitSekerci** [bounswe/bounswe2023group4#198]
### Problem Definition

Decide the font for mobile app in for easy use.

### Problem Context

* Fonts must be chosen for theming in whole app easily. 

### Acceptance Criteria

* Choose and import the fonts to resource folders in app.

### Suggested Solutions

* You may look google fonts for good examples.

**Comment by aemresafak** [comment]
The pr has been approved and merged. Thanks yigido
