### ISSUE TITLE
Arranging Gradle Dependencies for Android Project

### ISSUE THREAD

**Issue by aemresafak** [bounswe/bounswe2023group4#199]
### Problem Definition

Gradle is a dependency management software that is used for Android dependencies. Some dependencies in our gradle file are currently obsolete. For instance compose bom version is at least 5 versions older than the current version. Someone should update the gradle dependencies.

### Suggested Solutions

Update the dependencies in gradle.

**Comment by YigitSekerci** [comment]
This issue is resolved in [this pr](https://github.com/bounswe/bounswe2023group4/pull/226). We can start our development from these dependencies.
