### ISSUE TITLE
Non-Functional Requirements

### ISSUE THREAD

**Issue by enfurars** [bounswe/bounswe2023group4#20]
### Problem Definition

We had a meeting with our team. During the meeting we have discussed about requirements and the subjects of the last lecture which was on 14.03.2023. We have decided to **make a research about Non-Functional requirements and add the non-functional requirements**, which we can decide on at the current stage of the project, **to our wiki page**.

### Problem Context

The PDFs [Lifecycle and Requirements](https://moodle.boun.edu.tr/pluginfile.php/1326665/mod_resource/content/1/Project%20Lifecycle%20and%20Introduction%20to%20Requirements.pdf) and [Requirements Specification](https://moodle.boun.edu.tr/pluginfile.php/1326668/mod_resource/content/1/Software%20Requirements%20Specification%20%28SRS%29.pdf) which are on our CMPE352 Moodle page will be our guidelines for this task. 

### Acceptance Criteria

- Share result of researches under this issue
- Decide on which Non-Functional requirements we can specify verifiably at this stage of the project
- Add Non-Functional requirements to wiki 

### Suggested Solutions

1. Team members can add their researches under this issue about Non-Functional requirements
2. Then, we can specify the requirements that are verifiable and can be decided at this stage
3. Then, I can add the specified requirements to wiki
4. After that, we can review it both in group and with our customer for further improvements

**Comment by AliNasra** [comment]
**Here are my proposals regarding non-functional requirements**
# Portability:
- The application should be available as a website on the web and an API on mobile phones.
# Convenience:
- The GUI should be non-exhausting to the human eye.
- Offline mode should be available where users can access info regarding their scores and miscellaneous reports on their performance.
# Speed:
- The website should have an average response time between 0.1 - 1 second. 
# Size:
- The application size on mobile phones shouldn't exceed 20 megabytes.
- Storage-demanding media shan't be supported by the application.
# Ease of use:
- Annotation shall be provided to illustrate incomprehensible aspects of the interface to the users.
- A short visual tutorial shall be prepared to acquaint the users with the application's interface.
# Security:
- Security protocols and provisions like KVKK shall be applied.

**Comment by enfurars** [comment]
**After some research I have come up with these possible requirements:**

## Portability and compatibility

- The website shall be able to run on Google Chrome, Yandex, Safari, Internet Explorer and Firefox without any extra work, any failure regarding its specified performance and scalability requirements and any change in its behavior.

_Some requirements regarding mobile usage may be added after asking our customer if they also want an application._

## Performance and scalability

- The website's page load time shall be maximum 6 seconds. 
- The website's page load time should be under 3 seconds on average.  

_Before deciding on scalability of the website we should discuss with our customer and ask several questions like:_

- _What is the current volume of users?_
- _What are the expectations about growth of volume of the users in the following 3 years?_
- _As of day one, how many users should the website handle?_

## Reliability, Maintainability, Availability

- The website should perform its functional requirements successfully 90 percent of the time. 
- The mean time to restore the system(MTTRS of the website) should not exceed 15 minutes in case of an error.
- The website should be available 95 percent of the time to users from TR.

## Security

- An unauthorized access to admin panel shall be blocked by defining different login flows and different user roles as user actions.
- All nicknames shall be different from each other.

## Localization

_These are localization requirements for Turkey. If our customer decides to enter global market, suitable localization requirements will be applied._

- The language of the website shall be Turkish.
- The date format shall be date.month.year.
- The context of the website shall be proper to the regulations of Turkey.
- The website shall be able to show Turkish characters without any problem.
- The sorting algorithms (if any) used in the website shall be according to Turkish alphabet. 

## Usability 

- Users should be adequately trained by aid of simple instructions when they first sign-up to the website.
- The appropriate user should be able to login to the system.
- The appropriate user should be able to post a new poll.
- The appropriate user should be able to predict on a poll.
- The appropriate user should be able to personalize his/her profile.

_Adequately trained users are considered to be the appropriate users for testable usability requirements._

**Comment by YigitSekerci** [comment]
Enes have written very comprehensive [comment](https://github.com/bounswe/bounswe2023group4/issues/20#issuecomment-1474520452) I guess. I just want to add one topic.

# Accesibility

**Comment by enfurars** [comment]
I have added the non-functional requirements that we have decided currently to [requirements wiki page](https://github.com/bounswe/bounswe2023group4/wiki/Requirements). Can someone check on it and close the my task?

**Comment by carmendetroit** [comment]
I checked, didn't see any inconsistency.
