### ISSUE TITLE
Setting up the navigation component for Android

### ISSUE THREAD

**Issue by aemresafak** [bounswe/bounswe2023group4#200]
### Problem Definition

Navigation component in android is used for navigating from one page to another. We should set a navigation component in android project to facilitate the navigation process. We must also configure the necessary dependencies for the navigation component.

### Suggested Solutions

Add the navigation dependencies and implement the navigation component.

**Comment by YigitSekerci** [comment]
This issue is resolved in (this pr)[https://github.com/bounswe/bounswe2023group4/pull/245]. Thx Ahmet.
