### ISSUE TITLE
Project Plan Update Frontend

### ISSUE THREAD

**Issue by selinisik** [bounswe/bounswe2023group4#202]
### Problem Definition

During the lecture, our instructor suggested adding extra milestones to the project plan for more frequent progress evaluations. Thus, we will determine where to insert these additional milestones in the program.

**Comment by selinisik** [comment]
I have updated frontend project plan according to the decided group milestones. Here is the [updated plan](https://github.com/bounswe/bounswe2023group4/wiki/Frontend-Project-Plan).

**Comment by simsekhebun** [comment]
The plan looks good and in sync with the other teams, I am closing the issue.
