### ISSUE TITLE
Project Plan Update Backend

### ISSUE THREAD

**Issue by simsekhebun** [bounswe/bounswe2023group4#204]
### Problem Definition

Our lecturer recommended including more milestones in the project plan for more frequent progress assessments. We will therefore choose where to add these extra milestones to the plan.

**Comment by simsekhebun** [comment]
Updated the backend project plan according to our newly added milestones. Here is [the plan](https://github.com/bounswe/bounswe2023group4/wiki/Backend-Project-Plan).

**Comment by selinisik** [comment]
The plan looks good and in sync with the other teams. Good job!
