### ISSUE TITLE
Sign-in page implementation

### ISSUE THREAD

**Issue by AliNasra** [bounswe/bounswe2023group4#205]
### Problem Definition

A sign-in page shall serve as the entrance that ushers the users into the world of polls. It's a rudimentary facet of any online platform.

### Acceptance Criteria

The team members shall examine the output, compare it to the mock-up, and check it against the design requirements.

### Suggested Solutions

The UI shall be implemented in accordance with the most recent mock-up design.

**Comment by selinisik** [comment]
Here is the updated sign-in UI 

![sign-in](https://github.com/bounswe/bounswe2023group4/assets/56879777/a2120735-4980-45f7-baf4-79d9db1f6e7c)

Here is my PR [#242](https://github.com/bounswe/bounswe2023group4/pull/242)

**Comment by enfurars** [comment]
LGTM
