### ISSUE TITLE
Learn unit testing in node.js

### ISSUE THREAD

**Issue by Sefik-Palazoglu** [bounswe/bounswe2023group4#206]
### Problem Definition

We want to be able to unit test our implementations when developing the backend of our project.

### Problem Context

This issue tracks the effort of the assignee to learn and use unit testing when developing with node.js

### Acceptance Criteria

The assignee understands how to use unit tests. 
Assignee should be able to help others in backend team to setup their testing environment.
Assignee shows examples of unit test results.

### Suggested Solutions

Assignee can check out Jest testing suite to use in node.js

**Comment by EmreBatuhan** [comment]
We have a working tets enviroment. This issue is over.
