### ISSUE TITLE
Prepare database for Authentication

### ISSUE THREAD

**Issue by Sefik-Palazoglu** [bounswe/bounswe2023group4#207]
### Problem Definition

We need to prepare our database for basic authentication. We need to handle user authentication in the backend. For this, we need to store some information in our database. This is intended to be for basic authentication, security details will be considered in the following weeks.

### Problem Context

In our design, authentication requires database capabilities. So we need to prepare a database schema.

### Acceptance Criteria

Assignee is able to show how their schema can be used for authentication with a small test in node.js.

### Suggested Solutions

Assignee may consider storing the hashes of passwords instead of actual passwords in the database.

**Comment by EmreBatuhan** [comment]
Database file has been commited and merged. This issue is over.
