### ISSUE TITLE
Research Google auth requirements for backend

### ISSUE THREAD

**Issue by Sefik-Palazoglu** [bounswe/bounswe2023group4#208]
### Problem Definition

Assignee will research how to implement authentication with Google account. Will share his findings with the group. Discuss how to implement this and what is required in database.

### Problem Context

Users should be able to login with their google accounts to our project.

### Acceptance Criteria

Assignee can explain and show how to handle Google authentication.
If applicable at the time, assignee prepares a demo (maybe with help from the front team)

### Suggested Solutions

There are packages that handle google authentication, assignee may study them and decide if they are useful.
Assignee can read Google's documentation about Google auth.

**Comment by Sefik-Palazoglu** [comment]
According to this resource https://developers.google.com/identity/sign-in/web/backend-auth?hl=tr ,
we need to use "google-auth-library" in node.js to verify the google tokens that come from the client.
After verification, we create a new user or authenticate an existing one.
Before all this, we need to go to [google developer console](https://console.cloud.google.com/projectselector2/apis/dashboard?pli=1&supportedpurview=project) to register our app to be able to handle google authentication.

**Comment by Sefik-Palazoglu** [comment]
I also watched these videos to get a better grasp at the subject:

- https://www.youtube.com/watch?v=NfvP8KtErNM
- https://www.youtube.com/watch?v=HtJKUQXmtok

**Comment by simsekhebun** [comment]
Since the research is done I am closing this issue.
