### ISSUE TITLE
Database Deployment

### ISSUE THREAD

**Issue by Sefik-Palazoglu** [bounswe/bounswe2023group4#209]
### Problem Definition

Our database needs to be deployed and we should be able to communicate with it (if we ever want to deploy our project). Assignees need to figure out how to deploy a database to a remote machine and manage it.

### Problem Context

Our database needs to be remote if we want to deploy our project.

### Acceptance Criteria

Database is deployed and we can communicate with it through node.js

### Suggested Solutions

Try free tier of AWS.

**Comment by Sefik-Palazoglu** [comment]
@simsekhebun deployed the mysql database with help from Amazon's RDS service. I connected to this database from MySqlWorkbench program from my computer and it works.
<img width="734" alt="Screenshot 2023-10-23 at 20 40 30" src="https://github.com/bounswe/bounswe2023group4/assets/44020012/10dc72eb-3da5-4807-9710-83a5d6c5227c">
Also, we tried to run our application and connect our node.js app to the remote database. We tested a signup function and we get username and hashed password in the database.
<img width="1009" alt="Screenshot 2023-10-23 at 20 41 56" src="https://github.com/bounswe/bounswe2023group4/assets/44020012/879e72b7-49c7-42f1-ae98-5be203b39173">

<img width="444" alt="Screenshot 2023-10-23 at 20 41 44" src="https://github.com/bounswe/bounswe2023group4/assets/44020012/49823685-ed8b-46f1-b30e-080bb6615fb9">

This is how it looks like in aws console.
![image (1)](https://github.com/bounswe/bounswe2023group4/assets/44020012/234a67fd-f75e-4741-95ab-c87b1ca7dc4b)

**Comment by simsekhebun** [comment]
Since we have done this task with @Sefik-Palazoglu I am closing this issue.
