### ISSUE TITLE
Learn unit testing in node.js

### ISSUE THREAD

**Issue by EmreBatuhan** [bounswe/bounswe2023group4#210]
Problem Definition
We want to be able to unit test our implementations when developing the backend of our project.

Problem Context
This issue tracks the effort of the assignee to learn and use unit testing when developing with node.js

Acceptance Criteria
The assignee understands how to use unit tests.
Assignee should be able to help others in backend team to setup their testing environment.
Assignee shows examples of unit test results.

Suggested Solutions
Assignee can check out Jest testing suite to use in node.js

**Comment by Sefik-Palazoglu** [comment]
Pull request is merged and closed. @EmreBatuhan and I prepared a testing environment. This issue is closed.
