### ISSUE TITLE
Sign-up page implementation

### ISSUE THREAD

**Issue by kutaysaran** [bounswe/bounswe2023group4#212]
### Problem Definition

A sign-up page shall be implemented to allow users to register and access specific system functionalities.

### Acceptance Criteria

Team members shall review the output, compare it with the mock-up, and ensure it aligns with the design requirements.

### Suggested Solutions

The UI shall be developed following the latest mock-up design.

**Comment by enfurars** [comment]
Main structure of sign-up page is done. Check [PR](https://github.com/bounswe/bounswe2023group4/pull/227).

**Comment by kutaysaran** [comment]
here is updated sign-up page UI
<img width="1440" alt="Ekran Resmi 2023-10-22 18 23 36" src="https://github.com/bounswe/bounswe2023group4/assets/74209499/e9e0fbe1-08dd-4026-9cf8-cb8d5e7ae5d9">

**Comment by enfurars** [comment]
Both PRs are merged which concludes this issue.
