### ISSUE TITLE
Learn gradle basics

### ISSUE THREAD

**Issue by YigitSekerci** [bounswe/bounswe2023group4#217]
### Problem Definition
We will use gradle in our android app constantly and every member should learn its basics. Since gradle may sometimes error prone learning the basics can help debugging possible bugs in gradle configuration. 

### Problem Context
Research for android app

### Acceptance Criteria
* Learn gradle basics
* Learn what gradle sync is

### Suggested Solutions
* Gradle may be overwhelming but we just need to learn what we need to do. No need to do very detailed document research.

**Comment by aemresafak** [comment]
I have studied Gradle and I have a good understanding of the basics. I know what Gradle is, what Gradle sync is, and some of the benefits of using Gradle in Android development. I am also aware that Gradle can be error-prone, but I believe that learning the basics will help me to debug possible bugs in Gradle configuration.

Here is a brief summary of what I have learned about Gradle:

Gradle is a build automation tool that is used for Android development to automate the process of building and publishing apps.
Gradle sync is the process of reconciling the changes that have been made to the project with the build configuration.
Some of the benefits of using Gradle in Android development include:
Automated build process
Dependency management
Build flexibility
I am confident that I can use my knowledge of Gradle to help our team develop and publish high-quality Android apps.

**Comment by YigitSekerci** [comment]
I have learned gradle basics from its official docs. Then, I have learned what is gradle sync and how to optimize it. While trying some gradle examples I have encountered many conflicts in dependencies. Thus, I have learned importance of dependency versions. With the help of the knowledge that I have gained in this research I have started to code our project.

**Comment by AliAlperenSonmez** [comment]
I have successfully acquired the fundamentals of Gradle, enabling me to work confidently with Gradle in our Android app development.I understand the concept of Gradle sync and its significance in the build process, allowing me to effectively diagnose and resolve Gradle-related issues when they arise. I have approached learning Gradle with a focus on practical knowledge, ensuring that I can efficiently configure and manage Gradle for our Android project without delving into unnecessary complexity.

**Comment by YigitSekerci** [comment]
We made a mistake by combining research issues. Because every members' finish time is different we couldn't close this issue on time. Due to these reason, this issue is completed one day after its deadline.
