### ISSUE TITLE
Learn dependency injection techniques

### ISSUE THREAD

**Issue by YigitSekerci** [bounswe/bounswe2023group4#219]
### Problem Definition
Every team member should learn dependency injection for resource optimizing. DI is very popular concept in android and has many benefits in apps.

### Acceptance Criteria
* Learn what dependency injection
* Learn why we use dependency injection
* Learn how to implement dagger hilt in android

### Suggested Solutions
* Since we will use dagger hilt for our dependency injection in app, members can look its documentation.

**Comment by YigitSekerci** [comment]
I have learned the dependency injection from Youtube guides then I have read the [official documentation](https://developer.android.com/training/dependency-injection). Then I have learned how to implement this concept. With that knowledge I have implemented network module for (this issue)[https://github.com/bounswe/bounswe2023group4/issues/223].

**Comment by aemresafak** [comment]
I have learned what dependency injection is and how it is used in kotlin. I also learnt about dagger hilt

**Comment by AliAlperenSonmez** [comment]
I have gained a comprehensive understanding of dependency injection, recognizing it as a crucial concept for optimizing resource management in Android app development.
