### ISSUE TITLE
Creating Mock-Ups for Mobile and Web applications

### ISSUE THREAD

**Issue by aemresafak** [bounswe/bounswe2023group4#22]
### Problem Definition

Although we defined many functional and non-functional requirements, we need to validate these requirements with our customer, Utkan Gezer.  We have to show stakeholders and team members what the system might look like in order to validate these requirements. We need to create mock-ups for this reason.

### Problem Context

Here is a description of a mock-up for clarification: A mock-up is a visual representation or a prototype of the user interface of a software system. It is used to show stakeholders and team members what the system might look like, and to gather feedback on the user interface design.

### Acceptance Criteria

We currently aim to release the application both as a web application and a mobile application. Thus, at least one mock-up must be created for both the web application and the mobile application. Only difference between the web application and mobile application should be how UI elements look, the functionality must be the same.

### Mock-up Types
- A user creates a poll
- A user sees a poll in his feed, and votes for the poll

### Suggested Solutions

For creating mock-ups, Figma or Balsamic Wireframe can be used.

**Comment by aemresafak** [comment]
https://www.figma.com/file/2uLwTTIdgKzCQh5s1U3oVg/Cmpe-352?node-id=2-669
Selin and I have created the mock-up. We need further review from our teammates. Currently, we are working on minor improvements to the design and going over the requirements.

**Comment by aemresafak** [comment]
Selin and I have created the mock-up. We need further review from our teammates. Currently, we are working on minor improvements to the design and going over the requirements.

**Comment by aemresafak** [comment]
https://github.com/bounswe/bounswe2023group4/wiki/Mock-up

**Comment by selinisik** [comment]
Can someone take a look at the mock-up page and close the issue?

**Comment by YigitSekerci** [comment]
🔥Looks good to me. Well done good work.
