### ISSUE TITLE
Learn build variant system

### ISSUE THREAD

**Issue by YigitSekerci** [bounswe/bounswe2023group4#221]
### Problem Definition
Build variants are essential parts of mobile apps and every member should learn what they are and how to switch between them for development.

### Acceptance Criteria
* Learn what build variants are.
* Learn how to switch build variants
* Learn how to change variant config

### Suggested Solutions
* Team members can look to official android guides.

**Comment by YigitSekerci** [comment]
I have learned the required information from [this official guide](https://developer.android.com/build/build-variants). 
I have downloaded and used a matrix variant selector for switching build variants.
I have learned how to modify variant specific information in gradle for example baseUrl according to variant. Then, I have implemented a code for [this issue](https://github.com/bounswe/bounswe2023group4/issues/222).

**Comment by aemresafak** [comment]
After diving deep into mobile app development, I've come to truly appreciate the nuances of build variants in the Android ecosystem. These tools empower developers like myself to generate multiple app versions from one codebase, making tasks like testing and deployment far more streamlined. Knowing how to effortlessly switch between these variants and alter their configurations has broadened my skillset and given me more control over the development process. The official Android guides were a treasure trove of information on this, and I'm grateful for the clarity they provided

**Comment by AliAlperenSonmez** [comment]
I have a clear understanding of build variants, which are crucial components of mobile app development, thanks to my research and learning. I can confidently switch between different build variants for development purposes, demonstrating my grasp of this essential concept. I have successfully modified variant configurations in a sample app, showcasing my ability to adapt and customize build variants as needed, following the guidelines from official Android resources.

**Comment by YigitSekerci** [comment]
We made a mistake by combining research issues. Because every members' finish time is different we couldn't close this issue on time. Due to these reason, this issue is completed one day after its deadline.
