### ISSUE TITLE
Implement the network module

### ISSUE THREAD

**Issue by YigitSekerci** [bounswe/bounswe2023group4#223]
### Problem Definition
Network module is one of the key dependency injection modules in android apps. Assigne should implement this module for project to prepare app for network requests.

### Problem Context
* Dependency injection

### Acceptance Criteria
* Implement network module

### Suggested Solutions
* You may look online projects for module examples.

**Comment by YigitSekerci** [comment]
I have implemented the network module in [this pr](https://github.com/bounswe/bounswe2023group4/pull/229). We may add some additional security or auth steps in it but it should be enough for now.

**Comment by aemresafak** [comment]
I have added some reviews on the pr. Check them please.

**Comment by YigitSekerci** [comment]
Pr is merged, issue is resolved.

**Comment by YigitSekerci** [comment]
Due to late reviews, I couldn't complete this issue on time. I had to wait for reviews for one more day.
