### ISSUE TITLE
Create Swagger Documentation Backend

### ISSUE THREAD

**Issue by EmreBatuhan** [bounswe/bounswe2023group4#232]
### Problem Definition

In order to clearly communicate with the other parts of the project, a swagger documentation is necessary.

**Comment by Sefik-Palazoglu** [comment]
Swagger documentation code has beed implemented in backend/authorization branch which will be merged to backend/development and then /development.

**Comment by Sefik-Palazoglu** [comment]
Pull Request is merged. This issue is closed.
