### ISSUE TITLE
Update wiki home page

### ISSUE THREAD

**Issue by YigitSekerci** [bounswe/bounswe2023group4#24]
### Problem Definition

Update wiki home page to make it similar and comprehensive.

### Acceptance Criteria

* Improve wiki home page for understanding wiki structure and repo better.

### Suggested Solutions

* Look old repos for ideas but don't COPY
* Look popular public repos

**Comment by selinisik** [comment]
@aemresafak Can you review the wiki home page and share your thoughts with us?

**Comment by aemresafak** [comment]
Home page looks comprehensive to me! Thank you for your efforts.
