### ISSUE TITLE
Updating wiki page for requirements

### ISSUE THREAD

**Issue by aemresafak** [bounswe/bounswe2023group4#25]
### Problem Definition

After the last 2 meetings prior to 19/03/2023, we had many discussions over the requirements. After the clarifications we have got from our customer, we have updated the requirements. Some parts are still missing, though we have mostly decided on them. Requirements about poll resolution should be added to the requirements list and wiki page corresponding to the requirements should be updated.

### Problem Context

This word file contains the current requirements we have. It lacks the part about poll resolution.
[Functional Design Requirements Proposals (2).docx](https://github.com/bounswe/bounswe2023group4/files/11012241/Functional.Design.Requirements.Proposals.2.docx)

**Comment by YigitSekerci** [comment]
I have updated the wiki page @aemresafak can you check ?

**Comment by aemresafak** [comment]
It contains the updated version of the requirements, well done 👏👏
