### ISSUE TITLE
Deploy the backend to EC2 

### ISSUE THREAD

**Issue by simsekhebun** [bounswe/bounswe2023group4#251]
### Problem Definition

We need to deploy our backend docker container to an EC2 instance.

**Comment by simsekhebun** [comment]
I have deployed our backend to an EC2 instance you can check our api docs[ here](http://ec2-3-121-205-89.eu-central-1.compute.amazonaws.com:8000/api-docs/).

**Comment by EmreBatuhan** [comment]
Deployed code has been tested and it is ready to go.
