### ISSUE TITLE
Deployment of the finalized product 

### ISSUE THREAD

**Issue by simsekhebun** [bounswe/bounswe2023group4#252]
### Problem Definition

We need to deploy our finalized product for our milestone 1 and our demo for next week.

**Comment by simsekhebun** [comment]
I have deployed our finalized product. It can be accessed through [here](http://ec2-3-78-169-139.eu-central-1.compute.amazonaws.com:3000/auth/sign-in).

**Comment by EmreBatuhan** [comment]
Deployed code has been tested and it is ready to go.
