### ISSUE TITLE
Implementing Poll Cards

### ISSUE THREAD

**Issue by AliNasra** [bounswe/bounswe2023group4#256]
### Problem Definition

The poll posts should be displayed in a proper and decent manner.

### Acceptance Criteria

The UI shall be submitted and reviewed by the members of the front-end team.

### Suggested Solutions

Ant Design was recommended for the implementation for convenience and expedience. The library shall be installed and used in the implementation.

**Comment by selinisik** [comment]
Due to some priority changes in Ali's tasks, i have completed this instead of him. Here is the pr [#279](https://github.com/bounswe/bounswe2023group4/pull/279)

**Comment by selinisik** [comment]
This pr is reviewed and merged. I am closing this issue.
