### ISSUE TITLE
Combining backend and frontend

### ISSUE THREAD

**Issue by AliNasra** [bounswe/bounswe2023group4#257]
### Problem Definition

The back-end services should be integrated with the front-end UI.

### Acceptance Criteria

The integration should be robust and fully functional. 

### Suggested Solutions

Representatives from the back-end and the front-end teams should tackle the responsibility of this task.

**Comment by AliNasra** [comment]
A meeting slated for 9:30 AM this morning will be held to discuss what can be done regarding this task.

**Comment by enfurars** [comment]
check [pr](https://github.com/bounswe/bounswe2023group4/pull/269)

**Comment by AliNasra** [comment]
The tasks required by this issue have been completed successfully. The issue shall be closed.
