### ISSUE TITLE
Authentication Info (Req 1.1.2.1.1) Research

### ISSUE THREAD

**Issue by YigitSekerci** [bounswe/bounswe2023group4#26]
### Problem Definition

We haven't decided the required information in authentication. We need to look similar authentication systems for required information and update wiki. 

### Problem Context
* Requirement 1.1.2.1.1

### Acceptance Criteria

* Look similar authentication systems.
* Find and discuss required information.
* Update wiki
* Utkan's approval

**Comment by enfurars** [comment]
I thought that our project is kind of a combination of forums, prediction/bet sites and entertainment platforms. I have searched for platforms which are similar to ours and tried to sign up and sign in to those platforms. Finally I have come up with some suggestions and possible requirements:

- Users shall sign up with an unused e-mail, unused nickname and a password.
- Users should get a verification mail to their e-mail address when they sign up.
- Users should be able to sign in using either their e-mail or nickname together with their password after they verify their mail addresses. 
- Passwords shall be at least 8 characters and shall contain at least three of the following:
     1. Lower case letters (a-z)
     2. Upper case letters (A-Z)
     3. Numbers (0-9)
     4. Special characters (e.g. !@#$%^&*)

**Comment by selinisik** [comment]
- Should we request information about their age?
-  Will there be anything we ask them to accept when signing up?

**Comment by enfurars** [comment]
I did not think about users' ages. I do not know if they are required. We can discuss this and ask to our customer. You are right we should have some provisions to be accepted by users like KVKK when they sign up.

**Comment by YigitSekerci** [comment]
I don't think we need their exact age but we need to know that whether they are older than certain threshold or not. We can achieve this with a simple checkbox in sign up. I don't know whether it is necessary or not.

**Comment by enfurars** [comment]
I have added requirements 1.1.2.1.1, 1.1.2.1.2, 1.1.2.1.3, 1.1.2.1.5 and modified the requirement 1.1.2.2.1 accordingly with my research and newly added requirements. Can someone check those and close this issue?

**Comment by carmendetroit** [comment]
I checked and I am closing. Thanks.
