### ISSUE TITLE
Automatically close inactive users' polls with no due date (Req 1.2.1.3) Research

### ISSUE THREAD

**Issue by YigitSekerci** [bounswe/bounswe2023group4#29]
### Problem Definition

We need to think about when to close inactive users polls with no due date to close them automatically. Discuss under this issue for possible solutions or may be come up with better idea instead of closing. Then, update wiki.

### Problem Context

* Requirement 1.2.1.3

### Acceptance Criteria

* Discuss and find possible solutions
* Update the wiki according to chosen solution

**Comment by AliNasra** [comment]
Taking into consideration the average retention rates, I propose a 60-day grace of no logins to close no-due-date polls of inactive users. You can check the average retention rates through this [website](https://www.geckoboard.com/best-practice/kpi-examples/retention-rate/). The average retention rate for 90+ days is 20%. Although these statistics are for mobile apps, I believe that a similar pattern can be observed for websites.

**Comment by skywllker** [comment]
It is hard to handle no-due-date polls, so my first suggestion is mandatory due dates. People who open the poll have to add a specific due date, also this idea will help us to ask users in order to ask the result of that poll. We can consider to add "not yet concluded" option for no due date polls.

**Comment by skywllker** [comment]
I decided to there is no need to consider inactive user situation. If we handle the poll system fair, user who open the poll shouldn't have any affect on poll process.
