### ISSUE TITLE
Continuous grading (Req 1.2.2.1) Research

### ISSUE THREAD

**Issue by YigitSekerci** [bounswe/bounswe2023group4#30]
### Problem Definition

We need to decide how to share the points when the poll options are not discrete. Find and discuss possible solutions for grading according to proximity then update wiki. 

### Problem Context

* Requirement 1.2.2.1

### Acceptance Criteria

* Discuss solutions
* Select the best solution for our project
* Update wiki

**Comment by AliNasra** [comment]
Recalling CmpE343, we usually estimated the values of probabilistic variables in particular intervals with a 90% confidence rate. Hence, I assume a 10% error is acceptable.

**Comment by AliAlperenSonmez** [comment]
## There are 3 possibilities in a continious poll:
1. The user is at top 50%. (i.e., at least 50% of the users have equal or worst guess then the user)
2. The user is at bottom 50%. 
3. Everyone makes the same guess.

1. If the user is at top 50%:
    * The user will get his/her point back.
    * Top 50% will be divided into 4 parts:
        1. The bottom 25% part will share %5 of the points of the losers.
        2. The next better division will share %15 of the points of the losers.
        3. The next better division will share %25 of the points of the losers.
        4. The top %25 division will share %45 of the points of the losers.
        5. Remaining 10% of the points will be burned to prevent point inflation.
    * Users will share points proportional to their deposited points.

2. The bottom 50% part will be the losers. They will lose all their money.

3. If everyone makes the same guess, the deposited points will be given back. No losers or winners.

**Comment by YigitSekerci** [comment]
> ## There are 3 possibilities in a continious poll:
> 1- The user is at top 50%. (i.e., at least 50% of the users have equal or worst guess then the user) 2- The user is at bottom 50%. 3- Everyone makes the same guess.
> 
> 1. If the user is at top 50%:
>    
>    * The user will get his/her deposited points back.
>    * Top 50% will be divided into 4 parts:
>      
>      1. The bottom 25% part will share %5 of the points of the losers.
>      2. The next better division will share %15 of the points of the losers.
>      3. The next better division will share %25 of the points of the losers.
>      4. The top %25 division will share %45 of the points of the losers.
>      5. Remaining 10% of the points will be burned to prevent point inflation.
>    * Users will share points proportional to their deposited points.
> 2. The bottom 50% part will be the losers. They will lose all their deposited points.
> 3. If everyone makes the same guess, the deposited points will be given back. No losers or winners.

I really liked the idea but I think there should be threshold for winning the bet. If all the users predictions are wrong we shouldn't give the closest %50 the points. (I guess)

**Comment by aemresafak** [comment]
@AliAlperenSonmez thank you for your efforts I think your idea is very cool and verifiable. However, I see that you just copied and pasted your comment into the requirements. However, system requirements must be written in the following format: The system shall ...
Please refer to #31.

**Comment by AliAlperenSonmez** [comment]
@aemresafak thanks for your attention. I edited the requirement.

**Comment by AliAlperenSonmez** [comment]
can somebody check and close the issue?

**Comment by AliNasra** [comment]
The task has been completed successfully, hence concluding this issue.

**Comment by selinisik** [comment]
I think the requirements you've written down in Wiki does not conform to the format of the rest of the requirements. You have created only one requirement in the wiki and it makes it harder to read the requirements in wiki page. Can you divide it into parts and subparts so that it is more readable? Please check requirements of the jury system for more details.
