### ISSUE TITLE
Implement Poll Logic

### ISSUE THREAD

**Issue by Sefik-Palazoglu** [bounswe/bounswe2023group4#302]
### Problem Definition

Our polls need to be implemented in backend. Frontend applications should be able to request, create polls and add and edit vote. 

### Problem Context

Endpoints for polls are implemented from the fundamentals issue. We need to make these endpoints work. https://github.com/bounswe/bounswe2023group4/issues/254

### Acceptance Criteria

All Endpoints work for polls described in https://github.com/bounswe/bounswe2023group4/issues/254. Although the endpoints are SUBJECT TO CHANGE. All changes need to be documented in this issue to keep track and/or a new issue.
According to [Milestone Report Backend Plan](https://github.com/bounswe/bounswe2023group4/blob/main/reports/m1_group4.md#backend-plans) this needs to be implemented this week.

### Suggested Solutions

Use https://github.com/bounswe/bounswe2023group4/issues/254 as a starting point.

**Comment by EmreBatuhan** [comment]
I have revised the code and it has the necessary properties. This issue is closed.
