### ISSUE TITLE
Implement profile screen UI

### ISSUE THREAD

**Issue by YigitSekerci** [bounswe/bounswe2023group4#311]
### Problem Definition

Profile page UI should be implemented with respect to app mock ups.

### Problem Context

* Profile screen mock up

### Acceptance Criteria

* Profile screen UI should be implemented.

**Comment by aemresafak** [comment]
I am sorry me was late and could not implements this in time. I had difficulitiy implement it. It was very hard  implement. It is overdue by one week and I am most deeply sorry for that. I ensure you that I will make up for the lost time. I sorry.

**Comment by YigitSekerci** [comment]
Ahmet forgot the closing this issue but he already did this task and it was very good well done Ahmet.
