### ISSUE TITLE
Update Mobile Project Plan

### ISSUE THREAD

**Issue by YigitSekerci** [bounswe/bounswe2023group4#315]
### Problem Definition

Since Alperen left the mobile team, we have to update project plan.

### Problem Context

* Mobile project plan.

### Acceptance Criteria

* Update project plan to meet milestone requirements.

**Comment by YigitSekerci** [comment]
I have updated mobile project plan and @AliNasra updated the combined project plan.

**Comment by AliNasra** [comment]
We have combined the plans and everything is going well!
