### ISSUE TITLE
Grading polls with indefinite due date (Req 1.2.2.3) Research, Discuss

### ISSUE THREAD

**Issue by YigitSekerci** [bounswe/bounswe2023group4#32]
### Problem Definition

We have requirement that says

> Polls with indefinite due dates shall not be subject to linear incremental grading. (TBD)

Some members couldn't understand the meaning of this requirement. Discuss this requirement and decide its necessity with team members.

### Problem Context

* Requirement 1.2.2.3

### Acceptance Criteria

* Discuss the requirement
* Update the wiki if necessary

**Comment by AliNasra** [comment]
Our system incorporates a level of flexibility that allows users to post polls with no due date. Initially, it was assumed that the grade a user gets correlates with the voting time. Due dates were important in this tentative grading system. Subsequently, it was proposed that the grading of no-due-date polls shouldn't adhere to the aforementioned rule. Nevertheless, the customer has conveyed his wish for the system to exhort people to contemplate and reconsider their choices: users should be able to ponder their choices free of any restrictions. Hence, this requirement shall be scrapped, and a time-independent grading shall be adopted.

**Comment by EmreBatuhan** [comment]
Ali Nasra is right. The poll grading system is not affected from the absence of the due date. This issue is closed.
