### ISSUE TITLE
Dockerization and redeployment of our backend 

### ISSUE THREAD

**Issue by simsekhebun** [bounswe/bounswe2023group4#336]
### Problem Definition

After the changes made on the backend we needed a redeployment of the current version.

**Comment by simsekhebun** [comment]
Done the new backend swagger document can be accesed through [here](http://ec2-3-121-205-89.eu-central-1.compute.amazonaws.com:8000/api-docs).

**Comment by Sefik-Palazoglu** [comment]
Backend is deployed and running fine.
