### ISSUE TITLE
UML Preliminary Research

### ISSUE THREAD

**Issue by AliNasra** [bounswe/bounswe2023group4#34]
### Problem Definition

As mentioned in the class, we are supposed to design a UML diagram, an important tool for any project's visual illustration. The group members need to get acquainted with the trappings of this edifice.

### Acceptance Criteria

A report should be submitted to the group detailing the foundational principles of a robust UML design. After thorough discussions and deliberations, a UML diagram that reflects the design requirements of the project should be created.

**Comment by AliNasra** [comment]
A UML design is a thorough representation of the project, incorporating multiple variations:
**Class Diagrams:**
They are very reminiscent of the OOP classes tackled in CMPE 160, incorporating classes with their fields, methods, and connections. This part focuses on the actors and elements of the system. You can check [those examples](https://www.lucidchart.com/pages/uml-class-diagram).
**Sequence Diagrams:**
Such diagrams accentuate the interactions among actors of a system through lifelines. Each diagram corresponds to a specific action. You can check [those examples](https://www.lucidchart.com/pages/uml-sequence-diagram).
**Use Case Diagrams:**
These diagrams demonstrate the functionalities multiple users can access and use and the different actions they might take. You can check [those examples](https://www.lucidchart.com/pages/uml-use-case-diagram).
**Activity Diagrams:**
Such diagrams adopt the flow chart model. You can check [those examples](https://www.visual-paradigm.com/guide/uml-unified-modeling-language/what-is-activity-diagram/).
**State Diagrams:**
They are very similar to CMPE 240's state diagrams with little additions. They include all the possible states of the application and the corresponding outputs and subsequent transition conditions. You can check [those examples](https://www.lucidchart.com/pages/uml-state-machine-diagram).

Lucidchart is a very beneficial website used for drawing such diagrams. In addition, it includes tutorials, detailing the syntax and general rules for creating those diagrams.

**Comment by aemresafak** [comment]
Thanks for your efforts @AliNasra. The information you've provided was very useful.
