### ISSUE TITLE
Requirements Points Inflation Prevention

### ISSUE THREAD

**Issue by EmreBatuhan** [bounswe/bounswe2023group4#35]
### Problem Definition

Points are the currency of our application which is used to enter polls. We have decided that every user will recieve some amount of points everyday. However, our current system does not have a way to dispose of these new points which may result in some users having excessive amount of points. This may result in point inflation.

### Acceptance Criteria

* Discuss ways of disposing of the excess points
* Select the best solution for our project
* Get okay from utkan

### Suggested Solutions

Right now selling users some kind of a stat upgrade or an item might be a good solution. This would also give the currency more uses other than poll participation which also solves the [point redundancy issue](https://github.com/bounswe/bounswe2023group4/issues/38).

**Comment by EmreBatuhan** [comment]
I suggest a ranking system where the users can buy ranks in the system. For example "experienced" rank can be sold for 1000 points and "master" rank can be sold for 10000 coins. I also suggest to make these ranks permanent but increase the rank cost significantly so that the users will always have a higher rank to buy.
This system would reduce the total number of points in the system and provide our currency more uses.

**Comment by aemresafak** [comment]
Maybe we can take %10 of total points in a poll as a system price. If total points placed are 10000, 1000 points would go to the system and remaining 9000 points would be split to winners. This is done commonly in applications such as 101 okey plus :D.

**Comment by enfurars** [comment]
As I have commented in #27 if we have a fixed cost for opening a poll inflation will be deduced. Additionally, I believe ranks or badges should be given by system automatically as they get points. We can discuss this.

**Comment by enfurars** [comment]
I have added a point system suggestion in #38 in which I a mechanism for inflation prevention is stated. Can you also check there.

**Comment by EmreBatuhan** [comment]
Poll opening fee and taking %10 of the winners profit from the winners is our decided solution for this problem.
Poll Closing
*Sytem shall take %10 of the winners profit

**Comment by selinisik** [comment]
I reviewed subrequirement 1.2.1.4.1 . I did not see any problems.
