### ISSUE TITLE
Searching among polls

### ISSUE THREAD

**Issue by AliAlperenSonmez** [bounswe/bounswe2023group4#36]
### Problem Definition

We need to determine a way to search or filter polls, such as enabling users to find and vote on specific polls.

### Acceptance Criteria

* Discuss solutions
* Select the best solution for our project
* Get okay from utkan

**Comment by EmreBatuhan** [comment]
For this issue, I suggest to use a search bar. It is pretty common but I think it will do the job. We already have the label system. We can search the input keywords among the labels, poll question, and the answers of the poll.

**Comment by selinisik** [comment]
I think we can split the search bar in two. Search by tags and search by keywords. With this method, we can first list the tags and filter them according to user entries. All tags can be listed if the user doesn't type anything in the search bar. This gives users access to all open tags and they can discover new topics they haven't seen before in polls. In the second part, we can perform the normal search.
