### ISSUE TITLE
Implement feed screen backend requests

### ISSUE THREAD

**Issue by YigitSekerci** [bounswe/bounswe2023group4#362]
### Problem Definition

Our feed page is implemented thanks to @aemresafak but we need to integrate it with backend. Assignee should complete this integration.

### Problem Context

- Feed screen.

### Acceptance Criteria

- Fully integrated feed screen.

**Comment by aemresafak** [comment]
i am still working on this issue as of 20 November. I will not be able to finish it in time. Task proved to be more challenging than I thought. There are many things I have difficulty implementing. Sorry for the delay.

**Comment by YigitSekerci** [comment]
Ahmet did a wonderful work in [this pr](https://github.com/bounswe/bounswe2023group4/pull/438). The task is concluded.
