### ISSUE TITLE
Decision to creating weekly effort page 

### ISSUE THREAD

**Issue by skywllker** [bounswe/bounswe2023group4#37]
### Problem Definition

Should we create weekly report page to write our working hours and our completed duties for tracking what we do for that project. Everyone create their own pages to write what they done week by week. 

### Acceptance Criteria

* Ask Utkan or Suzan hoca to complete that issue

**Comment by aemresafak** [comment]
We discussed this issue with Suzan Uskudarli. She mentioned that she explicitly wanted previous years' groups to create and fill the weekly effort page. Thus, this year it is not necessary to create a weekly effort page. @YigitSekerci and @selinisik and me were together during the discussion with Suzan hoca. Can you confirm and close the issue @YigitSekerci @selinisik ?
