### ISSUE TITLE
Dockerization and redeployment of our backend

### ISSUE THREAD

**Issue by simsekhebun** [bounswe/bounswe2023group4#396]
### Problem Definition

We have to redeploy our backend for the changes made and added features.

**Comment by simsekhebun** [comment]
I have [dockerized ](https://hub.docker.com/repository/docker/hebunsimsek/backend4/general) and deployed our backend which can be accessed [here](http://ec2-3-121-205-89.eu-central-1.compute.amazonaws.com:8000/api-docs/).

**Comment by enfurars** [comment]
Well done
