### ISSUE TITLE
Introduction Page of Selin Işık

### ISSUE THREAD

**Issue by aemresafak** [bounswe/bounswe2023group4#4]
As described in #1, each team member should introduce themselves in the wiki page conforming to the template. Currently, introduction page for Selin Işık is missing. Please, refer to the #1 for more details.

**Comment by selinisik** [comment]
I've created my introduction page as decribed in #1. Here is the link  of my page [Selin Işık](https://github.com/bounswe/bounswe2023group4/wiki/Selin-I%C5%9F%C4%B1k)
