### ISSUE TITLE
Creating a wiki page for the meeting notes of 25 March 2023

### ISSUE THREAD

**Issue by aemresafak** [bounswe/bounswe2023group4#40]
### Problem Definition

The team had a meeting at 25 March 2023 12:00. @aemresafak was assigned with the task of taking meeting notes. Now it is his duty to create a wiki page for the meeting notes of 25 March 2023. The wiki page should conform the standards of other meeting notes wiki pages.

**Comment by aemresafak** [comment]
https://github.com/bounswe/bounswe2023group4/wiki/Seventh-Meeting-Notes can someone please check this and close the issue?

**Comment by enfurars** [comment]
Nice work Ahmet. The meeting notes are suitable for general meeting notes template and contains important points of our meeting.
