### ISSUE TITLE
Point System

### ISSUE THREAD

**Issue by Sefik-Palazoglu** [bounswe/bounswe2023group4#405]
### Problem Definition

Point system should be implemented according to the requirements. Users need to have points, spend them to create polls and vote.

### Problem Context

For the milestone, we need to make Point system up and running since closing polls depends on this.

### Acceptance Criteria

Point system is implemented and working in accordance with events happening to polls. (Create Poll, Poll ends with result etc.)

**Comment by EmreBatuhan** [comment]
Point system code has been merged two days ago and now successfully working. We are know discussing the logic behind point management when user changes vote but I think this is a seperate issue from this.
