### ISSUE TITLE
Creating the Use Case Diagram

### ISSUE THREAD

**Issue by enfurars** [bounswe/bounswe2023group4#41]
### Problem Definition

A well designed **use case diagram** is needed to represent all possible interactions between the system(the prediction poll platform) and all types of users that can use the system. 
Note: Types of users can be found in [requirements page](https://github.com/bounswe/bounswe2023group4/wiki/Requirements). 

### Problem Context

The PDF [System design](https://moodle.boun.edu.tr/pluginfile.php/1214896/mod_resource/content/3/System%20Design%20with%20UML.pdf ) which is on our CMPE352 Moodle page will be our guideline for this task. Also research done by @AliNasra at #34 will be beneficial for us during the work. 

### Acceptance Criteria

- As stated in the problem definition all possible interactions shall be represented and added to wiki page.
- While preparing the diagram, functional requirements of the project shall be considered and diagram shall follow the requirements.
- During the preparation of the diagram if any missing functional requirement is noticed by team members, it should be reported and resolved under this issue before going on with the diagram.

**Comment by enfurars** [comment]
Use case diagrams are prepared by @enfurars, @aemresafak, @selinisik and @YigitSekerci and then shared with the team members. The latest versions of them will be uploaded to wiki later on.

**Comment by enfurars** [comment]
Additionally I was responsible for taking notes of missing requirements during the work of use case diagrams and we have noticed that the **requirement about viewing the existing comments** is missing. It will be added to requirements page as well.

**Comment by enfurars** [comment]
I have added the missing requirement about viewing the comments as the requirement 1.1.4.5.

**Comment by EmreBatuhan** [comment]
The use case diagrams have been created. They may need revision however the current state is up to date.
