### ISSUE TITLE
UML: Class Diagrams 

### ISSUE THREAD

**Issue by AliNasra** [bounswe/bounswe2023group4#42]
### Problem Definition

Class diagrams are important tools in project representation. Our task is to design a class diagram according to the criteria stated in the lecture slides and the conventions in the real world.

### Problem Context

After some discussion in the last group meeting, it was decided to prioritize working on class diagrams among our primary issues. To that end, part of the group would dedicate their efforts to advancing as much as possible.

### Acceptance Criteria

A preliminary diagram must be submitted for collective evaluation.

**Comment by AliNasra** [comment]
A draft was submitted to the group for scrutiny and review. Indeed, there were some remarks regarding the absence of some details in the diagram. As a consequence, we can discuss the group's proposals in the comments. Nevertheless, in general, we envisage the work on the sequence diagram would complement the work on the class diagram, shedding light on the shortcomings and obscurities of the current model.

**Comment by EmreBatuhan** [comment]
The class diagram has been created. It might need revision however the current state is up to date.
