### ISSUE TITLE
Improving the JSON response of the /polls/{pollId} endpoint

### ISSUE THREAD

**Issue by AliNasra** [bounswe/bounswe2023group4#428]
### Problem Definition

In order to view a poll, a lot of information has to be passed down the line so that the vote page UI functions properly.

### Acceptance Criteria

The frontend is capable of retrieving data from the backend server.

### Suggested Solutions

I will forward an example structure used in the mock data that worked before to @Sefik-Palazoglu.

**Comment by AliNasra** [comment]
Here is an example of an ideal structure for the page:
{
      "id": 1,
      "question": "What is your favorite color?",
      "tags": ["Color", "Favorite"],
      "creatorName": "Zehra Kaya",
      "creatorId": 6327697326,
      "creatorUsername":  "zehra.kaya",
      "creatorImage": "https://www.w3schools.com/howto/img_lights_wide.jpg",
      "isCustomPoll": false,
      "options": [
        {
          "id": 1,
          "title": "Red",
          "votes": 10
        },
        {
          "id": 2,
          "title": "Blue",
          "votes": 15
        },
        {
          "id": 3,
          "title": "Green",
          "votes": 25
        },
        {
          "id": 4,
          "title": "Yellow",
          "votes": 35
        }
      ],
      "closingDate": "2023-06-18",
      "rejectVotes": "5 days",
      "isOpen": true,
      "comments": [
        {
          "userId": 34892738947,
          "comment": "I love the color red!"
        },
        {
          "userId": 340537547,
          "comment": "Blue has always been my favorite."
        },
        {
          "userId": 98432934,
          "comment": "Why isn't purple on the list?"
        }
      ]
    }

**Comment by Sefik-Palazoglu** [comment]
See https://github.com/bounswe/bounswe2023group4/pull/429 , closing this issue.
