### ISSUE TITLE
Requirements Page Rearrangement 

### ISSUE THREAD

**Issue by skywllker** [bounswe/bounswe2023group4#45]
### Problem Definition

There exist same requirements and related requirements at different places, so requirement page should be rearranged.

**Comment by EmreBatuhan** [comment]
We have made progress in this issue, however, we are stuck with the problem of jury and moderator section similarities. We dont want to change the meaning of the requirements but some entries are explaining similar procedures. I request some help from the writers of these sections @selinisik and @aemresafak.

**Comment by aemresafak** [comment]
System sends the join the request and moderators decide to accept or decline. They are related but can you tell me how to explain the capabilities of moderators in the system requirements? Clearly moderators are users I don't think it should be explained in system requirements. I hope I understand the problem correctly. Can you elaborate on this please?

**Comment by EmreBatuhan** [comment]
Both jury and moderator sections tell the join-the-jury procedure. So, I thought it would be more appropriate to combine this topic under a section. However, this topic consists of both user actions and system actions therefore these sections have to be seperated as @aemresafak said. I guess the best action to take will be to mention the related parts for these sections.
