### ISSUE TITLE
Frontend choice padding problem

### ISSUE THREAD

**Issue by Sefik-Palazoglu** [bounswe/bounswe2023group4#452]
### Problem Definition

When user does not select `openVisibility` field when creating a poll, the number of votes should not be visible to any users that view that poll.
<img width="436" alt="Screenshot 2023-11-26 at 14 22 19" src="https://github.com/bounswe/bounswe2023group4/assets/44020012/4818277d-7739-48dc-bc9e-fcfb2e40a5fa">
Consider this response from backend. This poll was created with `openVisibilty: false`. As a consequence, `voter_count` fields are returned as null. I suspect the problem stems from this reason.

Returning to the actual problem.
<img width="1095" alt="Screenshot 2023-11-26 at 14 23 49" src="https://github.com/bounswe/bounswe2023group4/assets/44020012/03f5e5a9-916c-4518-85dd-5f4d9285b244">
This is an example of a poll created with `openVisibility: true`.

<img width="1118" alt="Screenshot 2023-11-26 at 14 24 22" src="https://github.com/bounswe/bounswe2023group4/assets/44020012/2a388978-227a-4b90-808b-ff6d04453f73">
This is an example of a poll created with `openVisibility: false`, so `voter_count` field, aka the numbers you render in the choice buttons are simply `null`.

Please consider that voter_count can be null and try to render accordingly.

**Comment by Sefik-Palazoglu** [comment]
I've assigned everyone in frontend to work on this, if any one person is available, they can remove others from the assignee list and start working on this issue.

**Comment by AliNasra** [comment]
The issue's solution has been approved in the pull request https://github.com/bounswe/bounswe2023group4/pull/455. This issue can be closed!
