### ISSUE TITLE
Unspecified closingDate Poll Render Problem

### ISSUE THREAD

**Issue by Sefik-Palazoglu** [bounswe/bounswe2023group4#454]
### Problem Definition

Consider this poll object taken from the backend through /polls or /polls/{pollId}
<img width="456" alt="Screenshot 2023-11-26 at 14 29 12" src="https://github.com/bounswe/bounswe2023group4/assets/44020012/f1f98702-6dac-4d19-acf6-de455f41c609">

Please note that `closingDate: null` and `rejectVotes: null` also. This can happen if the user does not specify a closing date for the poll when creating the poll.
Currently when I try to view a poll like that, I get redirected to the /feed page. I assume this is because there is a problem with rendering the poll if these fields are null.
Please look into this.

### Suggested Solutions

<img width="473" alt="Screenshot 2023-11-26 at 15 36 46" src="https://github.com/bounswe/bounswe2023group4/assets/44020012/187edfa0-ff95-478d-a194-ea079eca26ba">
This is a poll like talked above. if you go to /vote/9, you get directed to /feed page. If we can render this properly, I think this issue is mostly solved.

**Comment by AliNasra** [comment]
The issue has been solved as in the pull request https://github.com/bounswe/bounswe2023group4/pull/455. Hence, this issue can be closed.
