### ISSUE TITLE
Logging the notes of the group's meeting - 30/03/2023

### ISSUE THREAD

**Issue by EmreBatuhan** [bounswe/bounswe2023group4#46]
### Problem Definition

Notes on the meeting slated for 30/03/2023 shall be recorded and reviewed with the team members.
The notes usually incorporate the following sections:
1- Meeting Information -> General information on the meeting's settings.
2- Agenda -> The purpose of the meeting.
3- Attendees -> List of group members who participated in the discussions.
4- Results -> Decisions taken during the meeting for future actions.

**Comment by EmreBatuhan** [comment]
Can someone review my [meeting notes page](https://github.com/bounswe/bounswe2023group4/wiki/Eighth-Meeting-Notes)?

**Comment by AliNasra** [comment]
The notes look good. Subsequently, we can consider the task finished and close the issue.
