### ISSUE TITLE
according to the feedbacks from milestone 1, requirements shall be updated

### ISSUE THREAD

**Issue by enfurars** [bounswe/bounswe2023group4#486]
### Problem Definition

I have asked our PO for feedbacks from milestone 1 and lots of vulnerabilities are provided about our requirements.

### Problem Context

![image](https://github.com/bounswe/bounswe2023group4/assets/110101098/83669f7a-f7c8-4d9f-b55c-1352d6ff2616)

### Acceptance Criteria

Each of the feedbacks given above should be addressed accordingly.

**Comment by enfurars** [comment]
[Requirements](https://github.com/bounswe/bounswe2023group4/wiki/Requirements) are updated. 

1.1.5.3.2 is deleted as suggested in the feedbacks.
1.2.2.14 is added.
1.2.3.12 is added.
1.2.3.13 is added.
1.1.4.1 is updated accordingly.
1.2.1.4.2 is deleted.
2.4.4 is added.

**Comment by enfurars** [comment]
For the inconsistency of 1.1.2 [mock up](https://github.com/bounswe/bounswe2023group4/wiki/Mock-up) is updated.

**Comment by EmreBatuhan** [comment]
I have reviewed the changes you have made and I think you covered all the lacking parts you mentioned in problem context. Good job!
