### ISSUE TITLE
according to the feedbacks from milestone 1, overview section shall be added to requirements

### ISSUE THREAD

**Issue by enfurars** [bounswe/bounswe2023group4#488]
### Problem Definition

Mission and vision of the project shall be explained briefly at the requirements part and glossary should be improved according to the feedback I got from PO.

**Comment by enfurars** [comment]
updated requirements page is [here](https://github.com/bounswe/bounswe2023group4/wiki/Requirements).

**Comment by AliNasra** [comment]
The overview section is concisely illustrative of the project's aims and aspirations. The glossary was indeed updated per the PO's shared reviews. Good job, Enes!

**Comment by enfurars** [comment]
Thank you, then I am closing the issue.
