### ISSUE TITLE
Complete Missing Requirements

### ISSUE THREAD

**Issue by skywllker** [bounswe/bounswe2023group4#49]
### Problem Definition

There are some missing requirements in requirements page and it should be completed. I expected from team members to comment below that missing requirements.

**Comment by EmreBatuhan** [comment]
In the grading section there is a good description for the continuous polls. However, grading section lacks description for multi-choice polls.

**Comment by YigitSekerci** [comment]
> In the grading section there is a good description for the continuous polls. However, grading section lacks description for multi-choice polls.

@skywllker Please let me know if this is handled. If so we can close this issue for now.

**Comment by skywllker** [comment]
Can you close that issue, I think it's done @YigitSekerci

**Comment by YigitSekerci** [comment]
> Can you close that issue, I think it's done @YigitSekerci

Did you update requirements according to the Batuhan's recommendation? What have you done can you give me the requirement number?

**Comment by YigitSekerci** [comment]
If you can give the reference to what have you done, you can speed up the review process significantly.

**Comment by YigitSekerci** [comment]
Okay seems reasonable we can discuss further in future if necessary.
