### ISSUE TITLE
Fix profile id - user id mismatch bug

### ISSUE THREAD

**Issue by selinisik** [bounswe/bounswe2023group4#507]
### Problem Definition

Backend team reported this bug, i will talk to them and handle this issue.

**Comment by selinisik** [comment]
@EmreBatuhan and I had a meeting and solved the issue. Here is the [PR](https://github.com/bounswe/bounswe2023group4/pull/533).

**Comment by EmreBatuhan** [comment]
Pr is merged so issue is over.
