### ISSUE TITLE
Creating Sequence Diagrams - Profiles

### ISSUE THREAD

**Issue by carmendetroit** [bounswe/bounswe2023group4#51]
### Problem Definition

Draw sequence diagrams for the profile system.

### Acceptance Criteria

The sequence diagrams need to be consistent with the instructor's lecture slides and uploaded to the wiki section after being reviewed by the other team members and instructor.

**Comment by enfurars** [comment]
Sequence diagrams for profile section are created by @enfurars and @carmendetroit then shared with other team members. Their latest versions will be uploaded to wiki after feedbacks.
