### ISSUE TITLE
Fix profile image related issues in polls

### ISSUE THREAD

**Issue by YigitSekerci** [bounswe/bounswe2023group4#513]
### Problem Definition

Profile images are not visible in polls but it should be. We may also add placeholders for them.

### Problem Context

* Feed page
* Vote page

### Acceptance Criteria

* Images should be visible in poll.

**Comment by aemresafak** [comment]
Images are not displayed since backend does not provide any images in the feed. They should fix this. @YigitSekerci @EmreBatuhan @Sefik-Palazoglu

**Comment by YigitSekerci** [comment]
Issue still persists in backend.

**Comment by aemresafak** [comment]
Backend is still tackling with the issue.

**Comment by aemresafak** [comment]
this issue is fixed with #625
