### ISSUE TITLE
Implement navigation to other users profile

### ISSUE THREAD

**Issue by YigitSekerci** [bounswe/bounswe2023group4#514]
### Problem Definition

Users should be able to other users profile pages as well. You may need to change the structure in profile for this behavior please comment for extra work.

### Problem Context

* Profile page

### Acceptance Criteria

* Users should be able to navigate to other users profile

**Comment by aemresafak** [comment]
I am still working on this issue. I am having a hard time fetching profile of the other users.

**Comment by YigitSekerci** [comment]
Ahmet finished this task in [this pr](https://github.com/bounswe/bounswe2023group4/pull/536). Well done Ahmet
