### ISSUE TITLE
Add Forgot Password feature to auth flow in mobile

### ISSUE THREAD

**Issue by YigitSekerci** [bounswe/bounswe2023group4#549]
### Problem Definition

Forgot password is implemented in backend and we need to develop the feature in the mobile.

### Problem Context

* Auth flow

### Acceptance Criteria

* Fully functional forgot password flow.

### Suggested Solutions

* You may look how frontend handled the issue.

**Comment by aemresafak** [comment]
I am still working on the edit profile issue. I could not spend any time on this task. I will finish this task this week!

**Comment by aemresafak** [comment]
Apparently, there is no support for forgot password in the backend. I am communicating with the backend team about the issue.

**Comment by aemresafak** [comment]
I have communicated with the backend team. They said that it was implemented but not yet deployed. I have written the code for it to function.

**Comment by aemresafak** [comment]
This issue is fixed in #612
