### ISSUE TITLE
Diagrams Revision - Sequence Diagrams

### ISSUE THREAD

**Issue by EmreBatuhan** [bounswe/bounswe2023group4#57]
### Problem Definition

We have written sequence diagrams, however, we want all of the sequence diagrams to follow some properties. There are quite a lot of sequence diagrams so we have decided that this issue will be more suited for two people.

**Comment by EmreBatuhan** [comment]
Sequence diagrams have been revised and they have been added to the wiki.

**Comment by aemresafak** [comment]
Looks good! Good job!
