### ISSUE TITLE
Creating Software Requirements Specification

### ISSUE THREAD

**Issue by aemresafak** [bounswe/bounswe2023group4#58]
### Problem Definition

Requirements have been designed by our team. However, no SRS (software requirements specification) has been prepared by the team. The team needs to review the requirements and prepare a SRS.

### Problem Context

SRS is important for introducing the project to all the stakeholders. Moreover, SRS is part of the deliverables required by the instructor Suzan Uskudarli.

### Suggested Solutions

The requirements should be revised and SRS shall be created according to the IEEE Std 830-1998.

**Comment by aemresafak** [comment]
I have created the SRS and uploaded it to the wiki. Check https://github.com/bounswe/bounswe2023group4/wiki/Software-Requirements-Specifications for more information.

**Comment by enfurars** [comment]
Well done @aemresafak. Page and SRS seems nice.
