### ISSUE TITLE
Diagrams Revision - Class Diagram

### ISSUE THREAD

**Issue by AliNasra** [bounswe/bounswe2023group4#59]
### Problem Definition

As a fundamental part of the deliverable to be handed in among other artifacts in the milestone report, class diagrams should be completed, pending an imminent review by the project owner. 

### Problem Context

Remarks offered by the team members regarding the initial draft were heeded and befittingly incorporated into the diagram. The final inspection by the project owner will be discussed.

**Comment by EmreBatuhan** [comment]
Class diagram have been revised and they have been added to the wiki. This issue is now closed.
