### ISSUE TITLE
Creating Scenarios

### ISSUE THREAD

**Issue by aemresafak** [bounswe/bounswe2023group4#62]
### Problem Definition

The team has created use case diagrams. However, scenarios are missing. Scenarios are textual information representing the use case. The team should create scenarios for each use case diagram.

**Comment by aemresafak** [comment]
@selinisik and I have created scenarios for each of the use case diagrams. Please refer to the wiki pages starting with Use case: for more details.

**Comment by selinisik** [comment]
@aemresafak and I finalized the scenarios and added the links to the latest versions in the sidebar. Can someone check it out and give feedback?

**Comment by YigitSekerci** [comment]
LGTM
