### ISSUE TITLE
deliverable 1 control project repository

### ISSUE THREAD

**Issue by skywllker** [bounswe/bounswe2023group4#63]
### Problem Definition

control the project repository: up to date wiki pages (as usual constant gardening). Do necessary changes.

### Acceptance Criteria

* There shouldn't be duplicate pages.
* Links should be work correctly.
* Wiki page should be seem organized.

**Comment by aemresafak** [comment]
@skywllker can you edit the issue title and description so that it is more clear what this issue is about? Moreover, deliverable 1 is not about writing a text. Can you update the description so that it encapsulates other parts of deliverable 1?

**Comment by YigitSekerci** [comment]
You should be more descriptive while creating issues. Use template more properly.

**Comment by YigitSekerci** [comment]
What is the status, deadline is very close.

**Comment by skywllker** [comment]
I have controlled project repository, you can close that issue @YigitSekerci

**Comment by YigitSekerci** [comment]
@skywllker Please delete the page for the mock up link. That's unnecessary and against the nature of wiki (I guess). We can share external links in our communication channels.

**Comment by skywllker** [comment]
I have deleted page: link to mock up
It seem's there are two mock up parts in our wiki page

**Comment by YigitSekerci** [comment]
LGTM

**Comment by skywllker** [comment]
I have added software requirements specification to sidebar under requirements

**Comment by YigitSekerci** [comment]
LGTM
