### ISSUE TITLE
Logging the notes of the group's meeting - 08/04/2023

### ISSUE THREAD

**Issue by selinisik** [bounswe/bounswe2023group4#64]
### Problem Definition

Notes on the meeting slated for 08/04/2023 shall be recorded and reviewed with the team members.
The notes usually incorporate the following sections:
1- Meeting Information -> General information on the meeting's settings.
2- Agenda -> The purpose of the meeting.
3- Attendees -> List of group members who participated in the discussions.
4- Results -> Decisions taken during the meeting for future actions.

### Acceptance Criteria

Update the wiki with new meeting notes according to meeting notes template.

**Comment by selinisik** [comment]
I have created the wiki page for [Eleventh Meeting Notes](https://github.com/bounswe/bounswe2023group4/wiki/Eleventh-Meeting-Notes). Can someone check?

**Comment by YigitSekerci** [comment]
LGTM
