### ISSUE TITLE
Milestone 1 - Fourth Deliverable RAM

### ISSUE THREAD

**Issue by enfurars** [bounswe/bounswe2023group4#65]
### Problem Definition

In our last meeting I am assigned to create the responsibility assignment matrix of the group. It should be created and added to wiki.

**Comment by enfurars** [comment]
I have completed the [RAM](https://github.com/bounswe/bounswe2023group4/wiki/RAM(Responsibility-Assignment-Matrix)) and added it to both wiki and sidebar. Can you check on it?

**Comment by YigitSekerci** [comment]
Looks good well done.
