### ISSUE TITLE
Milestone 1 - Fourth Deliverable Communication Plan

### ISSUE THREAD

**Issue by enfurars** [bounswe/bounswe2023group4#66]
### Problem Definition

In our last meeting I am assigned to create the communication plan of the group. It should be created and added to wiki.

**Comment by enfurars** [comment]
I have created the [communication plan](https://github.com/bounswe/bounswe2023group4/wiki/Communication-Plan) and added it to both wiki and sidebar. Can someone check on it?

**Comment by selinisik** [comment]
That looks awesome, nice work.
