### ISSUE TITLE
Fourth Deliverable Project Plan

### ISSUE THREAD

**Issue by YigitSekerci** [bounswe/bounswe2023group4#67]
### Problem Definition

We need project plan for milestone report. Please write project plan according to our old issues. Don't forget to look pdfs.

### Problem Context

* [Milestone Report](https://github.com/bounswe/bounswe2023group4/wiki/Milestone-1-Report)

### Acceptance Criteria

* Write project plan according to slides in Moodle.

### Suggested Solutions

* You may look old repos but it is discouraged to do so.

**Comment by YigitSekerci** [comment]
Seems like the [page](https://github.com/bounswe/bounswe2023group4/wiki/Project-Plan) is created but there is some much work to do. @selinisik will update the tasks.

**Comment by skywllker** [comment]
I have created project plan page, can you control and contribute? @selinisik

**Comment by selinisik** [comment]
I have updated the issue and dependencies tables. Can someone check the final version of the [Milestone-1-Project-Plan](https://github.com/bounswe/bounswe2023group4/wiki/Milestone-1-Project-Plan) ?

**Comment by YigitSekerci** [comment]
Future plan looks vague I guess but don't know what should we do. Maybe Moodle lesson header can be used?? I recall that we talked about docker in P.S for example.

**Comment by selinisik** [comment]
I updated the future plans section with the predictions I made based on the titles in Moodle. Can someone check the final version [Milestone-1-Project-Plan](https://github.com/bounswe/bounswe2023group4/wiki/Milestone-1-Project-Plan) ?

**Comment by YigitSekerci** [comment]
New version looks better nice work.
