### ISSUE TITLE
Milestone 1 - Second Deliverable - Mock Up

### ISSUE THREAD

**Issue by YigitSekerci** [bounswe/bounswe2023group4#68]
### Problem Definition

We have mock-ups but they need to be updated according to changes in requirements and scenarios.

### Problem Context

* #58 
* #62

### Acceptance Criteria

* Update the mock-ups
* Update the wiki

**Comment by selinisik** [comment]
@YigitSekerci  I have updated the mock ups and they are ready to be reviewed. Please check them out and report if something is missing.

**Comment by YigitSekerci** [comment]
LGTM
