### ISSUE TITLE
Deliverable 1 issue tracking

### ISSUE THREAD

**Issue by skywllker** [bounswe/bounswe2023group4#69]
### Problem Definition

Keep track of tasks, bugs, and other project-related issues until that milestone 1. Control every issue until now.

### Acceptance Criteria 

* Every issues' labels should be correct.
* Every issue must follow our issue guideline

**Comment by YigitSekerci** [comment]
Did you check issue labels ? What is the status?

**Comment by aemresafak** [comment]
Please keep in mind that issues must be descriptive. When other people look at an issue, everybody should understand more or less the same thing. Can you please be more descriptive both in title and in description? Unfortunately, next time we will have to close issues like this.

**Comment by skywllker** [comment]
I have controlled issues and made necessary changes. Now, every closed issue are done and assigned at least one person.

**Comment by YigitSekerci** [comment]
Ok that's enough for this issue I guess
