### ISSUE TITLE
API Research - AliNasra

### ISSUE THREAD

**Issue by EmreBatuhan** [bounswe/bounswe2023group4#72]
### Problem Definition

Every member needs to utilize at least one API as well as offer an API function.

### Acceptance Criteria

The API must be reviewed by the other team members.

**Comment by AliNasra** [comment]
I have identified the functionalities that should be incorporated into our miniature model.
1) Logging in
2) Signing up
3) Logging out
4) Posting Polls
5) Tagging Polls
6) Commenting on polls
7) Casting votes in polls 
8) Sharing achievements 
9) Sending Jury invitations 
10) Accepting Jury invitations
11) Sending friend requests
12) Accepting friend requests
13) Reporting polls 
14) Deleting polls 
15) Editing polls
16) Closing polls
17) Viewing Timeline

Currently, I am investigating public APIs that can be employed while implementing those functionalities. 
Check [1](https://github.com/public-apis/public-apis), [2](https://github.com/public-api-lists/public-api-lists)

**Comment by AliNasra** [comment]
Currently, I have found potential contender APIs that are apparently convenient for some functionalities.
### Posting Polls & Viewing Timeline
I believe that [Poll API](https://docs.pollsapi.com/) is a suitable candidate for this task. It is flexible, easy to use, and in line with the majority of the design requirements pertinent to polls and their characteristics.
### Tagging Polls
I am nominating [TextRazor](https://www.textrazor.com/docs/rest#topics) for the job. It seems to be easy to use and demonstrates well-regarded performance. Its drawback though is the stringent limitations imposed on free users. 
### Final Remarks
Those tags would be scrutinized more to determine their feasibility and compatibility with our design requirements and aspirations. In the next meeting, the team members would be briefed on relevant details and consulted regarding the suitability of these choices.

**Comment by AliNasra** [comment]
It has been decided that I will be employing the **Poll API** in our practice app. This concludes the task.
