### ISSUE TITLE
API Research - aemresafak

### ISSUE THREAD

**Issue by EmreBatuhan** [bounswe/bounswe2023group4#73]
### Problem Definition

Every member needs to utilize at least one API as well as offer an API function.

### Acceptance Criteria

The API must be reviewed by the other team members.

**Comment by aemresafak** [comment]
http://www.omdbapi.com/


The Open Movie Database (OMDb) is an online platform that provides a comprehensive collection of information about movies and TV shows. It was created to serve as a centralized database for all types of movie-related data and has become a valuable resource for movie fans, researchers, and developers.

OMDb offers detailed information about movies and TV shows, including plot summaries, cast and crew information, release dates, ratings, reviews, and much more. The data is collected from various sources, including users, critics, and other online databases.

The platform provides an API that allows developers to integrate OMDb data into their applications. This enables developers to create movie-related apps, websites, and tools that leverage the vast amount of data available on OMDb.

OMDb is free to use for non-commercial purposes and relies on donations to cover its operational costs. The platform is community-driven, and users are encouraged to contribute by adding new data, correcting errors, and providing feedback.

**Comment by aemresafak** [comment]
This will do.
