### ISSUE TITLE
API Research - AliAlperenSonmez

### ISSUE THREAD

**Issue by EmreBatuhan** [bounswe/bounswe2023group4#74]
### Problem Definition

Every member needs to utilize at least one API as well as offer an API function.

### Acceptance Criteria

The API must be reviewed by the other team members.

**Comment by AliAlperenSonmez** [comment]
I found an API which can be usefull for polls about exchange rates:
# Exchange Rates API
https://exchangerate.host/#/
![api_cmpe352](https://user-images.githubusercontent.com/72912553/235295857-9b77aed8-c4c7-4325-8d6f-dd6176eee6f4.jpg)

- It is free and reliable.

**Comment by aemresafak** [comment]
Nice api alperen. It will do.
