### ISSUE TITLE
API Research - EmreBatuhan

### ISSUE THREAD

**Issue by EmreBatuhan** [bounswe/bounswe2023group4#75]
### Problem Definition

Every member needs to utilize at least one API as well as offer an API function.

### Acceptance Criteria

The API must be reviewed by the other team members.

**Comment by EmreBatuhan** [comment]
I have found some useful API's for our application.

1. Google maps 
2. Twitter 
In my opinion being able to add different kinds of resources to the polls will be a very interesting option for our application. Users could add these at comments or at a section about poll information. 

3. Chatgpt 
4. IBM Watson natural language understand 
We have decided that our system would tag the polls so an tagging API would be very useful in our application.
5. Firebase cloud messaging
Notifications for the application

**Comment by EmreBatuhan** [comment]
I have chosen my API as API Ninjas.
They have quite a lot of info about a lot of topics and they have 50000 request limit per month which is enough for our current state. I will use country information from this API for our practice app.

**Comment by AliNasra** [comment]
The API seems appealing and convenient to our scale of deployment. This concludes the issue.
