### ISSUE TITLE
API Research - enfurars

### ISSUE THREAD

**Issue by EmreBatuhan** [bounswe/bounswe2023group4#76]
### Problem Definition

Every member needs to utilize at least one API as well as offer an API function.

### Acceptance Criteria

The API must be reviewed by the other team members.

**Comment by enfurars** [comment]
I have searched for a lot of APIs in the internet and come up with two good ones. 
First one is **OpenWeatherMap**: This API provides weather data for locations around the world. We can use it to display current weather conditions, forecasts, and other weather-related information on our platform. The API is free to use for up to 60 API calls per minute.
Other one is **The OpenBadges API**: This is a free and open standard for issuing and sharing digital badges. It provides a flexible framework for defining badges and tracking user achievements, and there are a number of open-source tools and libraries available for implementing the OpenBadges API in our project. 

We can use the weather API for presenting our members with a current and past data for their weather related predictions.

We can use the badge API for creating new badges and issuing them for different members and we can also track their achievements.

**Comment by enfurars** [comment]
I have chosen the 3rd party API OpenWeatherMap from above and suggested **the** **feature current weather conditions**. For this purpose I have created an API that GETs current weather for only Istanbul to illustrate an example usage. Also, another weather condition can be POSTed for another city like Ankara but it is not a that realistic scenario. My pull requests are merged which concludes this issue.
