### ISSUE TITLE
API Research - selinisik

### ISSUE THREAD

**Issue by EmreBatuhan** [bounswe/bounswe2023group4#77]
### Problem Definition

Every member needs to utilize at least one API as well as offer an API function.

### Acceptance Criteria

The API must be reviewed by the other team members.

**Comment by selinisik** [comment]
I have also found an alternative API for our Practice App which is [Reqres](https://reqres.in/). This API is made for practice and contains fake data, so we will not change the information in a working API in our POST requests and it contains all types of request which is quite useful for our Practice App.

**Comment by aemresafak** [comment]
This closes the issue. Thank you for efforts.
