### ISSUE TITLE
Django Tutorial

### ISSUE THREAD

**Issue by EmreBatuhan** [bounswe/bounswe2023group4#88]
### Problem Definition

We have decided to use Django in our practice application. However, our team needs a tutorial on Django. I will research necessary concepts and make a tutorial on these topics.

### Acceptance Criteria
Make a tutorial on these topics:

- [ ] Django installation
- [ ] Django URL management and routers
- [ ] Django views ,viewtemplates and viewsets
- [ ] Django models and serializers
- [ ] Sending requests to 3rd party APIs in Django
- [ ] Django REST Framework API basics and filtering

**Comment by AliNasra** [comment]
Having attended the tutorial session, I believe that Batuhan did a great job in elaborating on the intricacies and trappings of Django, having demonstrated an example code and analyzed the existent functionalities. Many thanks, Batuhan. This concludes this issue.
