### ISSUE TITLE
Swagger Tutorial

### ISSUE THREAD

**Issue by AliNasra** [bounswe/bounswe2023group4#96]
### Problem Definition

Swagger is a sophisticated tool user Swagger-compatible APIs. We are required to hand in Swagger-style documentation in fulfillment of the Project's requirements.

### Suggested Solutions

I will be investigating the simplest ways to create swagger documentation. I will be providing a written handout so team members can refer continuously to the notes with no need of holding a meeting.

**Comment by AliNasra** [comment]
1- **We will be initially installing multiple libraries**
In the terminal of the IDE you are using, write the following commands one by one
pip install pyyaml
![1](https://github.com/bounswe/bounswe2023group4/assets/52269552/7c7496ed-4a16-40b2-9351-794b8fe91e93)
pip install uritemplate
![2](https://github.com/bounswe/bounswe2023group4/assets/52269552/5e76f943-e5b0-4719-bd89-eb787e3c5765)
2- **Go to urls.py in the API folder**
![3](https://github.com/bounswe/bounswe2023group4/assets/52269552/bf170fb5-3c81-4318-98e0-98efdeed28d5)
3- **add the following line**
from rest_framework.schemas import get_schema_view
![4](https://github.com/bounswe/bounswe2023group4/assets/52269552/ef888e1a-595b-463d-8af1-ed68e2105bed)
4- **Add the following line in urlpatterns**
path('api_schema',get_schema_view(title = 'API Schema', description = 'API documentation'), name = 'api_schema'),
![5](https://github.com/bounswe/bounswe2023group4/assets/52269552/ab82dd14-897d-41d9-8d8e-1c9049d9a246)
5- **Check the documentation after running the server**
Use the link http://127.0.0.1:8000/api/api_schema
![7](https://github.com/bounswe/bounswe2023group4/assets/52269552/518265b0-852f-422b-9a05-b23642846f29)
6- **Install Swagger using the command**
pip install django-rest-swagger
![6](https://github.com/bounswe/bounswe2023group4/assets/52269552/ced039bc-4216-4b3e-a877-9ca53b1365ab)
7- **Go to the settings.py file**
In the TEMPLATES list, insert the following line into DIR os.path.join(BASE_DIR, 'templates')
![8](https://github.com/bounswe/bounswe2023group4/assets/52269552/c8d65fc1-c895-4e0b-9640-05d424bfdb35)
8- **Under the API directory, create a new folder. Call it templates**
![9](https://github.com/bounswe/bounswe2023group4/assets/52269552/0a9e1c8b-1db5-4228-a536-6ca4dc830476)
9- **In the templates folder, create the file docs.html**
10- **Copy the code in the [link ](https://gist.github.com/dotja/6da4783e3f1f1e1dd569a116660e9c42)"Check the third step."**
11- **Back to the URL.py, add the following lines in urlpatterns**
from django.views.generic import TemplateView
 path('docs/', TemplateView.as_view( template_name='docs.html', extra_context={'schema_url':'api_schema'}), name='swagger-ui'),
![11](https://github.com/bounswe/bounswe2023group4/assets/52269552/5371c614-4b3a-4ed4-bec2-c180072b9d89)
12- **Check the documentation after running the server**
Use the link http://127.0.0.1:8000/api/swagger-ui

**Comment by enfurars** [comment]
Well done @AliNasra. Can you also provide a wiki page and link for feature references?

**Comment by AliNasra** [comment]
Thanks @enfurars for the feedback. I have created the required wiki page and attached the necessary links both on the home page and in the sidebar. You can find the corresponding entry titled "Swagger Tutorial" under the research subsection in the sidebar. This concludes the task.
