### ISSUE TITLE
Log the meeting notes to wiki 10.05.2023

### ISSUE THREAD

**Issue by enfurars** [bounswe/bounswe2023group4#98]
### Problem Definition

I have taken meeting notes of our latest meeting for milestone2. Now it should be uploaded to wiki in the correct format as well.

**Comment by enfurars** [comment]
I have created the [meeting notes 15](https://github.com/bounswe/bounswe2023group4/wiki/Fifteenth-Meeting-Notes) page and added it to navigator as well. Can someone check it and close the issue?

**Comment by AliAlperenSonmez** [comment]
seems good
